import React,{useEffect,useRef,useState} from 'react';
import './arko.css';
import {ReplyFeedback} from './knowledge';
import mascot from './assets/arko-mascot.png';
async function api(path:string,data?:any){const r=await fetch('/api'+path,{method:data===undefined?'GET':'POST',headers:data===undefined?{}:{'Content-Type':'application/json'},credentials:'same-origin',body:data===undefined?undefined:JSON.stringify(data)});const body=await r.json();if(!r.ok)throw new Error(body.error||'Please try again.');return body;}
const countryNames:Record<string,string>={IN:'India',AE:'United Arab Emirates',GB:'United Kingdom',US:'United States',OTHER:'Another country'};
const labels:Record<string,string>={goal:'What you want to achieve',industry:'Your industry',country:'Company country',budget:'Budget context',timing:'When you want to start',assets:'What you already have',notes:'Anything else to consider'};
function Mark(){return <span className="arko-art avatar-art"><img src={mascot} alt="" /></span>}
function FullArko(){return <span className="arko-art full-arko"><img src={mascot} alt="Arko, Aurigin’s friendly blue and yellow AI mascot, waving hello" /></span>}

export function ArkoAdmin(){const[data,setData]=useState<any>(null),[selected,setSelected]=useState<any>(null),[error,setError]=useState('');useEffect(()=>{api('/admin/arko').then(setData).catch(e=>setError(e.message));},[]);return <section><h2>Arko conversations</h2><p>Review the customer’s words alongside the extracted brief. Anonymous conversations have not yet become leads.</p>{error&&<p role="alert">{error}</p>}{data&&<><p>{data.calls} AI attempts · {data.failures} failed attempts. Example conversations make no AI calls.</p><div className="grid two"><div>{data.conversations.map((c:any)=><article className="scope-card" key={c.id}><h3>{c.brief.goal||'New conversation'}</h3><p>{c.leadId?'Saved lead':'Anonymous brief'} · {c.turns} turns · {new Date(c.updatedAt).toLocaleString()}</p><button className="button secondary" onClick={()=>api('/admin/arko/'+c.id).then(setSelected).catch(e=>setError(e.message))}>Read conversation</button></article>)}{!data.conversations.length&&<p>No Arko conversations yet.</p>}</div><div>{selected&&<><h3>Project brief</h3><dl>{Object.entries(selected.brief).map(([k,v])=><React.Fragment key={k}><dt><strong>{k}</strong></dt><dd>{Array.isArray(v)?v.join(', '):String(v)||'Not discussed'}</dd></React.Fragment>)}</dl><h3>Conversation</h3>{selected.messages.map((m:any)=><article className="scope-card" key={m.id}><strong>{m.role==='user'?'Visitor':'Arko'} · {m.source}</strong><p style={{whiteSpace:'pre-wrap'}}>{m.content}</p></article>)}</>}</div></div></>}</section>;}
export default function Arko({config,Proposal}:any){
 const [chat,setChat]=useState<any>(null),[text,setText]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[edit,setEdit]=useState(false),[draft,setDraft]=useState<any>(null),[stage,setStage]=useState('chat'),[slots,setSlots]=useState<any>(null),[slot,setSlot]=useState(''),[quote,setQuote]=useState<any>(null),[meeting,setMeeting]=useState<any>(null);
 const [contact,setContact]=useState<any>({name:'',email:'',phone:'',company:'',country:'IN',industry:'Architecture',contactPermission:false,marketingPermission:false}),[briefConfirmed,setBriefConfirmed]=useState(false),[custom,setCustom]=useState('');
 const end=useRef<HTMLDivElement>(null),input=useRef<HTMLTextAreaElement>(null),actionTitle=useRef<HTMLHeadingElement>(null),bookingKey=useRef<string>('');
 async function run(fn:()=>Promise<void>){setBusy(true);setError('');setNotice('');try{await fn();}catch(e:any){setError(e.message);}finally{setBusy(false);}}
 async function refresh(){const c=await api('/arko');setChat(c);return c;}
 useEffect(()=>{document.title='Arko by Aurigin';run(async()=>{const c=await api('/arko/session',{});setChat(c);if(c.linked){const m=await api('/me').catch(()=>null);if(m?.id===c.leadId&&m?.unlocked){setQuote(await api('/quote'));setMeeting(m.bookings.find((b:any)=>b.status==='confirmed'));setStage('quote');}}});},[]);
 useEffect(()=>{if(chat?.messages.length>1)end.current?.scrollIntoView({behavior:'smooth',block:'nearest'});},[chat?.messages.length]);
 useEffect(()=>{if(stage!=='chat')actionTitle.current?.focus();},[stage]);
 async function send(message=text){if(!message.trim()||busy)return;setText(message);await run(async()=>{const c=await api('/arko/message',{message,revision:chat.revision,requestId:crypto.randomUUID()});setChat(c);setText('');});input.current?.focus();}
 async function openBooking(){await run(async()=>{if(!chat.brief.goal||!chat.brief.services.length){setDraft(structuredClone(chat.brief));setEdit(true);setNotice('Add a goal and service direction, then review your brief.');return;}if(chat.linked){setSlots(await api('/availability'));setStage('booking');}else{setContact((c:any)=>({...c,country:countryNames[chat.brief.country]?chat.brief.country:'IN',industry:chat.brief.industry||'Architecture'}));setStage('contact');}});}
 async function reserve(){await run(async()=>{if(!bookingKey.current)bookingKey.current=crypto.randomUUID();const result=await api('/booking',{start:slot,idempotencyKey:bookingKey.current});setMeeting(result.booking);setQuote(await api('/quote'));setStage('quote');});}
 const ready=Boolean(chat?.brief.goal&&chat?.brief.services.length);
 if(!chat)return <main className="arko-loading"><h1>Meeting Arko…</h1>{error&&<><p role="alert">{error}</p><button onClick={()=>location.reload()}>Try again</button><a href="/quote">Open the form instead</a></>}</main>;
 return <main className="arko-page">
  <div className="arko-heading"><div><p className="eyebrow">A LITTLE CLARITY. A BETTER NEXT STEP.</p><h1>Meet Arko<span> by Aurigin</span></h1><p>Your ambition, shaped into a project. Start with a conversation.</p></div><div className="arko-welcome-art"><FullArko/><a className="arko-form-link" href="/quote">Prefer the form? ↗</a></div></div>
  <div className="arko-layout">
   <section className="arko-chat" aria-label="Conversation with Arko">
    <div className="arko-chat-top"><div className="arko-avatar"><Mark/></div><div><strong>Arko</strong><span>AI project assistant · {chat.ai==='connected'?'AI connected':'Preview mode'}</span></div><button className="text-button" disabled={busy} onClick={()=>run(async()=>{await refresh();})}>Refresh</button><button className="text-button" disabled={busy} onClick={()=>run(async()=>{setChat(await api('/arko/new',{}));setStage('chat');setText('');setEdit(false);setQuote(null);setMeeting(null);setSlots(null);setBriefConfirmed(false);})}>New project</button></div>
    <div className={'arko-status '+(chat.ai==='connected'?'connected':'')}>{chat.notice}</div>
    <div className="arko-messages" role="log" aria-label="Messages" aria-live="polite" aria-relevant="additions">
     {chat.messages.map((m:any)=><article className={'arko-message '+m.role} key={m.id}><span className="arko-speaker">{m.role==='user'?'You':'Arko'}{m.source==='example'?' · example':m.source==='system'?' · project guide':''}</span><p>{m.content}</p>{m.role==='assistant'&&<ReplyFeedback messageId={m.id}/>}</article>)}
     {busy&&<p className="arko-thinking" role="status">Working on your next step<span>…</span></p>}<div ref={end}/>
    </div>
    {error&&<div className="arko-error" role="alert">{error}</div>}{notice&&<div className="arko-notice" role="status">{notice}</div>}
    {stage==='chat'&&<><div className="arko-suggestions">{chat.ai==='connected'&&!chat.linked&&chat.suggestions.map((s:string)=><button key={s} disabled={busy} onClick={()=>send(s)}>{s}</button>)}{chat.ai==='unavailable'&&chat.messages.length===1&&<button disabled={busy} onClick={()=>run(async()=>setChat(await api('/arko/example',{})))}>Explore an example conversation ↗</button>}{!chat.linked&&<button disabled={busy} onClick={()=>{setDraft(structuredClone(chat.brief));setEdit(true);}}>Edit my brief</button>}</div>
    <form className="arko-composer" onSubmit={e=>{e.preventDefault();send();}}><label className="sr-only" htmlFor="arko-message">Message Arko</label><textarea id="arko-message" ref={input} maxLength={2000} rows={2} value={text} onChange={e=>setText(e.target.value)} disabled={chat.linked} placeholder={chat.linked?'Your brief is saved. Continue to booking or your proposal.':chat.ai==='connected'?'Tell Arko what you have in mind…':'AI connects later. Explore the example or edit your brief.'} onKeyDown={e=>{if(e.key==='Enter'&&!e.shiftKey&&!e.nativeEvent.isComposing){e.preventDefault();send();}}}/><button aria-label="Send message" disabled={busy||!text.trim()||chat.linked}>↑</button></form><p className="arko-fine">{chat.ai==='connected'?'AI suggestions can be mistaken. Review your brief before continuing.':'Preview uses no live AI calls.'} Prices appear only after a confirmed consultation.</p></>}
    {stage==='contact'&&<section className="arko-action"><p className="eyebrow">SAVE YOUR BRIEF / CHOOSE A TIME</p><h2 ref={actionTitle} tabIndex={-1}>Let’s make the introduction.</h2><p>A few contact details let us save your project and arrange your consultation.</p>{config.mode==='DEMO'&&<button className="text-button" onClick={()=>setContact({...contact,name:'Demo visitor',email:`arko-${Date.now()}@studio.invalid`,phone:'+919000000000',company:'Studio North (Demo)'})}>Use synthetic demo details</button>}<form onSubmit={e=>{e.preventDefault();run(async()=>{const r=await api('/arko/enroll',{revision:chat.revision,contact,briefConfirmed});setChat(r.conversation);setSlots(await api('/availability'));setStage('booking');});}}><div className="arko-fields">{[['name','Your name'],['company','Company'],['email','Email'],['phone','Phone with country code']].map(([k,l])=><label key={k}>{l}<input required type={k==='email'?'email':k==='phone'?'tel':'text'} value={contact[k]} onChange={e=>setContact({...contact,[k]:e.target.value})}/></label>)}<label>Company country<select value={contact.country} onChange={e=>setContact({...contact,country:e.target.value})}>{Object.entries(countryNames).map(([v,l])=><option value={v} key={v}>{l}</option>)}</select></label><label>Industry<select value={contact.industry} onChange={e=>setContact({...contact,industry:e.target.value})}>{[...new Set(['Architecture','Interior design','Real estate','Construction','Other',contact.industry])].map(v=><option key={v}>{v}</option>)}</select></label></div><label className="check"><input required type="checkbox" checked={briefConfirmed} onChange={e=>setBriefConfirmed(e.target.checked)}/>This brief reflects my initial needs. Detailed scope and delivery assumptions still need review.</label><label className="check"><input required type="checkbox" checked={contact.contactPermission} onChange={e=>setContact({...contact,contactPermission:e.target.checked})}/>Aurigin may contact me about this project and consultation.</label><label className="check"><input type="checkbox" checked={contact.marketingPermission} onChange={e=>setContact({...contact,marketingPermission:e.target.checked})}/>Also send me occasional Aurigin updates (optional).</label><p className="arko-fine"><a href={config.privacy||'/privacy'}>Privacy notice</a> · Booking is free and does not obligate purchase.</p><button className="button" disabled={busy}>Save brief & find a time ↗</button></form><button className="text-button" disabled={busy} onClick={()=>setStage('chat')}>← Back to conversation</button></section>}
    {stage==='booking'&&<section className="arko-action"><p className="eyebrow">A CONVERSATION WITH ARJUN</p><h2 ref={actionTitle} tabIndex={-1}>Find a time to talk.</h2><p>Times below are in {Intl.DateTimeFormat().resolvedOptions().timeZone}. {config.mode==='DEMO'?'These are sample appointments.':'Your confirmation appears after a successful reservation.'}</p><div className="arko-slots">{slots?.slots.slice(0,28).map((s:any)=><button key={s.start} aria-pressed={slot===s.start} className={slot===s.start?'selected':''} onClick={()=>{setSlot(s.start);bookingKey.current='';}}>{new Date(s.start).toLocaleString([],{weekday:'short',month:'short',day:'numeric',hour:'numeric',minute:'2-digit'})}</button>)}</div>{!slots?.slots.length&&<p>No times are available right now. You can ask Arjun to arrange another time.</p>}<button className="button" disabled={busy||!slot} onClick={reserve}>{config.mode==='DEMO'?'Confirm sample consultation':'Confirm consultation'}</button><button className="text-button" disabled={busy} onClick={()=>run(async()=>{setSlots(await api('/availability'));setSlot('');})}>Refresh times</button><button className="text-button" disabled={busy} onClick={()=>run(async()=>{const r=await api('/waitlist',{});setNotice(r.message);})}>Request another time</button><p className="arko-fine">Reserved allocation: {slots?.reservedMinutes} minutes plus a buffer. Final scope and start date are discussed with Arjun.</p></section>}
    {stage==='quote'&&<section className="arko-action"><p className="eyebrow">YOUR NEXT CHAPTER</p><h2 ref={actionTitle} tabIndex={-1}>Your provisional estimate.</h2>{meeting&&<p className="arko-confirmed">✓ Consultation confirmed{config.mode==='DEMO'?' in this demo':''} · {new Date(meeting.start).toLocaleString()}</p>}{quote?.pricing?<><Proposal q={quote}/><a className="button" href={'/api/proposal.pdf?version='+quote.id}>Download proposal ↓</a><details><summary>Explore a different delivery level</summary><p>We start with the complete level. Focused and lean levels need Aurigin to confirm the exact deliverables before approval.</p><div className="actions"><button className="button secondary" disabled={busy} onClick={()=>run(async()=>setQuote(await api('/negotiate',{tier:'max'})))}>Complete</button><button className="button secondary" disabled={busy} onClick={()=>run(async()=>setQuote(await api('/negotiate',{tier:'medium'})))}>Focused</button><button className="button secondary" disabled={busy} onClick={()=>run(async()=>setQuote(await api('/negotiate',{tier:'low'})))}>Lean</button></div></details></>:<p>{quote?.message||'Arjun will review this scope and confirm the next step.'}</p>}<button className="text-button" disabled={busy} onClick={()=>run(async()=>setQuote(await api('/quote')))}>Refresh proposal</button><details><summary>Ask for a change or human review</summary><form onSubmit={e=>{e.preventDefault();run(async()=>{const r=await api('/custom-request',{reason:custom,type:'Arko handover'});setNotice(r.message);setCustom('');});}}><label>Your request<textarea required minLength={5} maxLength={4000} value={custom} onChange={e=>setCustom(e.target.value)}/></label><button className="button secondary" disabled={busy}>Send review request</button></form></details><a className="text-button" href="/quote">Open full project controls →</a></section>}
   </section>
   <aside className="arko-brief" aria-label="Your project brief"><div className="arko-brief-title"><p className="eyebrow">BUILT AS WE TALK</p><span>↗</span></div><h2>Your project brief</h2><p className="arko-brief-intro">A shared starting point. You can correct anything before saving.</p>
    {edit&&draft?<form onSubmit={e=>{e.preventDefault();run(async()=>{setChat(await api('/arko/brief',{brief:draft,revision:chat.revision}));setEdit(false);});}}><fieldset><legend>Service direction (up to six)</legend>{config.services.map((s:any)=><label className="check" key={s.id}><input type="checkbox" checked={draft.services.includes(s.id)} disabled={!draft.services.includes(s.id)&&draft.services.length>=6} onChange={e=>setDraft({...draft,services:e.target.checked?[...draft.services,s.id]:draft.services.filter((x:string)=>x!==s.id)})}/>{s.name}</label>)}</fieldset>{Object.entries(labels).map(([k,l])=><label key={k}>{l}{k==='country'?<select value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}><option value="">Not discussed yet</option>{Object.entries(countryNames).map(([v,n])=><option key={v} value={v}>{n}</option>)}</select>:<textarea rows={2} maxLength={1200} value={draft[k]} onChange={e=>setDraft({...draft,[k]:e.target.value})}/>}</label>)}<button className="button" disabled={busy}>Save brief changes</button><button type="button" className="text-button" onClick={()=>setEdit(false)}>Cancel</button></form>:<><dl><dt>Service direction</dt><dd>{chat.brief.services.length?chat.brief.services.map((id:string)=><span className="arko-tag" key={id}>{config.services.find((s:any)=>s.id===id)?.name||id}</span>):'Let’s find the right fit.'}</dd>{Object.entries(labels).filter(([k])=>k!=='notes'||chat.brief.notes).map(([k,l])=><React.Fragment key={k}><dt>{l}</dt><dd>{k==='country'?countryNames[chat.brief[k]]||chat.brief[k]||'Not discussed yet':chat.brief[k]||'Not discussed yet'}</dd></React.Fragment>)}</dl>{!chat.linked&&<button className="text-button" disabled={busy} onClick={()=>{setDraft(structuredClone(chat.brief));setEdit(true);}}>Edit brief ↗</button>}</>}
    {ready&&chat.recommendation&&<details className="arko-scope"><summary>Explore suggested scope</summary>{chat.recommendation.services.map((s:any)=><article key={s.id}><h3>{s.name}</h3><p>{s.why}</p>{['C','D'].includes(s.readiness)&&<strong>Discovery and delivery review needed</strong>}<ul>{s.scope.deliverables.map((d:string)=><li key={d}>{d}</li>)}</ul><p><strong>You supply:</strong> {s.scope.supplies.join('; ')}</p><p><strong>Excludes:</strong> {s.scope.exclusions.join('; ')}</p><p>{s.scope.timeline}; final timing confirmed with Arjun.</p></article>)}<p className="arko-fine">Suggested scope caps are assumptions for discussion, not an agreed specification.</p></details>}
    {stage==='chat'&&<button className="button arko-continue" disabled={busy||edit} onClick={openBooking}>{ready?'Choose a consultation ↗':'Shape my brief ↗'}</button>}<div className="arko-steps"><span>01 Tell us your ambition</span><span>02 Shape a useful scope</span><span>03 Meet Arjun & see your estimate</span></div><p className="arko-fine">No pressure. No obligation to buy.</p>
   </aside>
  </div>
 </main>;
}
