import test from 'node:test';
import assert from 'node:assert/strict';
import {Store} from '../server/store.ts';
import {createApp} from '../server/app.ts';
import {emptyBrief} from '../server/arko-model.ts';
import {seedKnowledge,publicKnowledge,reviewTurn,knowledgeChecks,launchPrices} from '../server/knowledge.ts';
import {randomUUID} from 'node:crypto';
const origin='http://127.0.0.1:4791';
async function fixture(){const store=new Store(':memory:');let received:any;
 const runtime=createApp(store,{origin,adminPassword:'knowledge-test-password',arkoModel:{respond:async input=>{received=input;return{value:{reply:'Arjun will confirm whether copywriting is included.',brief:emptyBrief,intent:'about',suggestions:[]}};}}});
 const server=runtime.app.listen(0,'127.0.0.1');await new Promise<void>(r=>server.once('listening',r));
 function agent(){let cookie='';return async(path:string,body?:any)=>{const r=await fetch(`http://127.0.0.1:${(server.address() as any).port}/api`+path,{method:body===undefined?'GET':'POST',headers:{Origin:origin,Cookie:cookie,'Content-Type':'application/json'},body:body===undefined?undefined:JSON.stringify(body)});if(r.headers.getSetCookie().length)cookie=r.headers.getSetCookie().map(x=>x.split(';')[0]).join('; ');return{status:r.status,body:await r.json()};};}
 return{store,agent,received:()=>received,close:async()=>{server.closeAllConnections();await new Promise<void>(r=>server.close(()=>r()));store.db.close();}};
}
test('Company library stays approved-only; drafts and private prices never enter retrieval',()=>{const s=new Store(':memory:');try{seedKnowledge(s);const count=s.list('KnowledgeEntry').length;seedKnowledge(s);assert.equal(s.list('KnowledgeEntry').length,count);assert.ok(knowledgeChecks(s).every(c=>c.pass));s.put('KnowledgeEntry',{draft:{title:'SECRET',content:'SECRET'},published:{title:'Internal pricing',category:'company',visibility:'internal',content:'CONFIDENTIAL RATE'}});assert.ok(!JSON.stringify(publicKnowledge(s,'internal pricing')).includes('CONFIDENTIAL'));assert.ok(!JSON.stringify(publicKnowledge(s,'copywriting')).includes('Replace this draft'));assert.equal(launchPrices.find(x=>x[0]==='portfolio')?.[5],22000);}finally{s.db.close();}});
test('Founder save, stale approval rejection, publish, unpublish and history',async()=>{const x=await fixture();try{const a=x.agent(),c=x.agent();assert.equal((await c('/admin/knowledge')).status,401);await a('/admin/login',{password:'knowledge-test-password'});const entry={title:'Copywriting for websites',category:'faq',content:'Copywriting is scoped separately by the team.',source:'Founder reviewed example',visibility:'public'};const saved=(await a('/admin/knowledge/save',{entry})).body;assert.equal((await a('/admin/knowledge/publish',{id:saved.id,revision:0,acknowledge:true})).status,409);assert.ok(!JSON.stringify(publicKnowledge(x.store,'copywriting')).includes(entry.content));assert.equal((await a('/admin/knowledge/publish',{id:saved.id,revision:saved.revision,acknowledge:true})).status,200);assert.ok(JSON.stringify(publicKnowledge(x.store,'copywriting')).includes(entry.content));assert.equal((await a('/admin/knowledge/history/'+saved.id)).body.length,1);const row=x.store.get(saved.id);await a('/admin/knowledge/unpublish',{id:row.id,revision:row.revision});assert.ok(!JSON.stringify(publicKnowledge(x.store,'copywriting')).includes(entry.content));}finally{await x.close();}});
test('Feedback ownership and repeat FAQ requests create review-only suggestions',async()=>{const x=await fixture();try{const a=x.agent(),c=x.agent(),other=x.agent();await a('/admin/login',{password:'knowledge-test-password'});const chat=(await c('/arko/session',{})).body;await other('/arko/session',{});const r=(await c('/arko/message',{message:'Is copywriting included, and can Arjun clarify the policy?',requestId:randomUUID(),revision:chat.revision})).body;assert.ok(x.received().knowledge.length>0);assert.ok(!JSON.stringify(x.received().knowledge).includes('22000'));const id=r.messages.at(-1).id;assert.equal((await other('/arko/feedback',{messageId:id,rating:'down'})).status,404);assert.equal((await c('/arko/feedback',{messageId:id,rating:'down',note:'Need an answer'})).status,200);await c('/arko/feedback',{messageId:id,rating:'up'});assert.equal(x.store.list('ArkoFeedback').length,1);const issue=x.store.list('QualityIssue').find(x=>x.issueType==='faq_gap');assert.ok(issue);const draft=(await a('/admin/quality/draft',{id:issue.id})).body;assert.equal(x.store.get(draft.id).published,null);assert.equal((await a('/admin/quality/draft',{id:issue.id})).body.id,draft.id);assert.equal((await a('/admin/quality/check',{})).body.passed,true);}finally{await x.close();}});
test('Repeated responses and unresolved topics are grouped without learning customer policy',()=>{const s=new Store(':memory:');try{seedKnowledge(s);const before=JSON.stringify(publicKnowledge(s,'hosting'));for(const id of ['c1','c2','c3'])reviewTurn(s,id,'Does Aurigin give free hosting?','Arjun will confirm hosting.',[{role:'assistant',content:'Arjun will confirm hosting.'}]);assert.equal(s.list('QualityIssue').find(x=>x.issueType==='faq_gap')?.count,3);assert.equal(s.list('QualityIssue').find(x=>x.issueType==='repetition')?.count,3);assert.equal(JSON.stringify(publicKnowledge(s,'hosting')),before);}finally{s.db.close();}});
