import express from 'express';
import {mountKnowledge,launchPrices} from './knowledge.ts';
import { randomBytes,scryptSync,timingSafeEqual } from 'node:crypto';
import { z } from 'zod';
import { Store,hash,uid,now } from './store.ts';
import { defaultPolicy,policySchema } from './policy.ts';
import { initialCatalogue,publicServices,currencies,reconcile } from './catalogue.ts';
import { registration,requirements,recommend,questions,alternatives } from './discovery.ts';
import { calculate,publicPricing,fingerprint,money } from './pricing.ts';
import { BookingService } from './booking.ts';
import { DemoCalendar,GoogleCalendar,sendEmail,sendWhatsApp,syncSheet,aiGuidance,geoSuggest,integrationStatus,verifySignature,checkConnections } from './adapters.ts';
import type { CalendarAdapter } from './adapters.ts';
import {mountArko} from './arko.ts';
import type {ArkoModel} from './arko-model.ts';
import { audit } from './audits.ts';
import { pdf } from './proposals.ts';
export function createApp(store:Store,options:{mode?:string,adminPassword:string,origin?:string,calendar?:CalendarAdapter,arkoModel?:ArkoModel}){
 const app=express(),mode=options.mode||'DEMO',demo=mode==='DEMO',origin=options.origin||'http://127.0.0.1:4173';
 if(!['DEMO','LIVE'].includes(mode))throw new Error('MODE must be DEMO or LIVE');
 if(!store.list('Policy').length)store.put('Policy',{value:defaultPolicy,status:'provisional',reason:'Founder prompt defaults'});
 if(!store.list('CatalogueVersion').length)store.put('CatalogueVersion',{value:initialCatalogue(),status:'development seeds'});
 const policy=()=>store.list('Policy')[0].value;const catalogue=()=>store.list('CatalogueVersion')[0];
 const booking=new BookingService(store,options.calendar||(demo?new DemoCalendar():new GoogleCalendar()),policy);
 const adminSalt=randomBytes(16),adminHash=scryptSync(options.adminPassword,adminSalt,64);const rate=new Map<string,{count:number,reset:number}>();
 app.disable('x-powered-by');
 app.use((req,res,next)=>{res.set({'Cache-Control':'no-store','X-Content-Type-Options':'nosniff','Referrer-Policy':'no-referrer','X-Frame-Options':'DENY','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; frame-ancestors 'none'"});if(!demo)res.set('Strict-Transport-Security','max-age=31536000');if(req.path.startsWith('/api')){const key=(req.socket.remoteAddress||'')+':'+(req.path.includes('login')||req.path.includes('resume')?'auth':'api');let r=rate.get(key);if(!r||r.reset<Date.now())r={count:0,reset:Date.now()+60000};r.count++;rate.set(key,r);if(r.count>(key.endsWith('auth')?20:240))return res.status(429).json({error:'Please wait before trying again.'});if(!['GET','HEAD','OPTIONS'].includes(req.method)&&!req.path.startsWith('/api/callbacks/')&&req.headers.origin!==origin)return res.status(403).json({error:'Origin not allowed'});}next();});
 app.use(express.json({limit:'64kb',verify:(req:any,_res,buf)=>{req.rawBody=buf;}}));
 const cookie=(req:any,name:string)=>(req.headers.cookie||'').split(';').map((s:string)=>s.trim()).find((s:string)=>s.startsWith(name+'='))?.slice(name.length+1);
 function session(req:any,role='client'){const token=cookie(req,role==='admin'?'aurigin_admin':role==='arko'?'aurigin_arko':'aurigin_session');if(!token)return null;return store.db.prepare('SELECT * FROM sessions WHERE token_hash=? AND role=? AND expires>?').get(hash(token),role,Date.now()) as any;}
 function requireRole(role:string){return(req:any,res:any,next:any)=>{const s=session(req,role);if(!s)return res.status(401).json({error:'Please sign in to continue.'});req.identity=s;next();};}
 function issue(res:any,owner:string,role='client'){const token=randomBytes(32).toString('hex');store.db.prepare('INSERT INTO sessions VALUES(?,?,?,?)').run(hash(token),owner,role,Date.now()+(role==='admin'?8:24)*3600000);res.cookie(role==='admin'?'aurigin_admin':role==='arko'?'aurigin_arko':'aurigin_session',token,{httpOnly:true,secure:origin.startsWith('https:'),sameSite:'strict',maxAge:(role==='admin'?8:24)*3600000,path:'/'});}
 const client=requireRole('client'),admin=requireRole('admin');
 const lead=(req:any)=>store.get(req.identity.owner,'Lead');
 const confirmed=(id:string)=>store.list('AuditEvent',id).some(x=>x.type==='booking_confirmed');
 function gate(id:string){if(!confirmed(id)){const e:any=new Error('Book a confirmed consultation to unlock your estimate.');e.status=403;throw e;}}
 function latestQ(id:string){return store.list('QuoteVersion',id)[0];}
 function publicQ(q:any,l:any){return{id:q.id,version:q.number,company:l.company,market:q.market,currency:q.currency,issued:q.created_at,expires:q.expires,status:q.status,demo,needs:q.needs,commercialTier:q.commercialTier||'max',reviewReasons:q.reviewReasons.map((reason:string)=>reason==='commercial_eligibility_review'?'Commercial eligibility needs agency confirmation':reason.replaceAll('_',' ').replace(':',': ')),terms:q.terms,benefits:q.benefits,pricing:publicPricing(q.pricing),hash:q.contentHash};}
 function makeQuote(l:any,r:any,route='custom',round=0,customLines?:any[],reason='Scope calculation',persist=true,tier:'max'|'medium'|'low'='max'){
 const cat=catalogue(),p=policy(),rec=recommend(r,l.country,p),reasons=[...rec.reasons];const lines:any[]=[];
 for(const service of rec.services){let row=cat.value.services.find((s:any)=>s.market===l.country&&s.service===service.id);const band=l.country==='IN'?launchPrices.find(x=>x[0]===service.id):null;if(row&&band)row={...row,standard:band[2]*100,tiers:{max:band[2]*100,medium:band[3]*100,low:band[4]*100},floor:band[5]*100};if(row&&l.country==='IN'&&row.service==='social')row={...row,standard:null};if(!row||['C','D'].includes(row.readiness)||row.standard===null||row.status==='suspended'){reasons.push(service.id+':discovery_needed');continue;}if(!demo&&row.status!=='approved-live'){reasons.push(service.id+':commercial_review');continue;}const original=row.service==='paid-media'?Math.max(row.standard,Math.round((r.mediaBudget||0)*15/100)):(row.tiers?.[tier]??row.standard);const scope=tier==='max'?row.scope:{...row.scope,deliverables:['Focused delivery level selected. Exact deliverables and caps will be confirmed with Aurigin before approval.'],exclusions:[...row.scope.exclusions,'Anything outside the selected delivery level']};if(tier!=='max')reasons.push(row.service+':focused_scope_review');lines.push({service:row.service,name:row.name,quantity:1,maxQuantity:1,unit:row.unit,cadence:row.cadence,eligible:true,original,floor:row.floor,cost:row.cost,benefitCost:p.benefitEnabled&&row.service==='portfolio'?p.benefitCost:0,scope});}
 if(r.mediaBudget)lines.push({service:'media-spend',name:'Media spend (separate client-paid budget)',quantity:1,maxQuantity:1,unit:'monthly budget',cadence:'monthly',eligible:false,original:r.mediaBudget,floor:0,cost:0,scope:{deliverables:['Client-paid advertising budget'],supplies:['Client advertising account'],exclusions:['Agency management fee'],timeline:'Monthly'}});
 const pricedLines=(customLines||lines).map((line:any)=>{const band=l.country==='IN'?launchPrices.find(x=>x[0]===line.service):null;return band?{...line,floor:Math.max(line.floor||0,band[5]*100)}:line;});const pricing=calculate(pricedLines,l.country,p,route,round);if(pricing.lines.some((line:any)=>line.eligible!==false&&line.floor!==null&&line.converted<line.floor)){const e:any=new Error('This amount is below the service floor. Please request team review or change the scope.');e.status=409;throw e;}if(pricing.economicStatus==='review')reasons.push('commercial_eligibility_review');
 const prev=latestQ(l.id);const value={number:(prev?.number||0)+1,previous:prev?.id||null,market:l.country,currency:currencies[l.country]||null,catalogueId:cat.id,policyId:store.list('Policy')[0].id,fxSnapshot:p.fx[l.country]||null,requirements:r,scopeFingerprint:fingerprint({services:rec.services.map(x=>x.id).sort(),pages:r.pages,details:r.details,country:l.country,tier}),commercialTier:tier,pricing,status:customLines?'revised pending approval':'provisional unlocked',reviewReasons:[...new Set(reasons)],needs:r.goals||r.problem,terms:p.terms,benefits:p.benefitEnabled&&lines.some(l=>l.service==='portfolio')?'Limited maintenance: '+p.benefitDays+' days; '+p.benefitHours+' support hours for the agreed site. Excludes new features, licences and rebuilding.':'No additional benefit is currently promised.',expires:new Date(Date.now()+p.validityDays*86400000).toISOString(),reason,benefitSnapshot:p.benefitEnabled&&lines.some(l=>l.service==='portfolio')?{days:p.benefitDays,hours:p.benefitHours,cost:p.benefitCost}:null,promotionBps:0};const contentHash=hash(value);if(!persist)return{...value,contentHash,id:'comparison',created_at:now(),owner:l.id};const q=store.put('QuoteVersion',{...value,contentHash},l.id);store.event('quote_version_created',l.id,{id:q.id,contentHash});if(pricing.priority.state==='priority')notifyFounder(l,'priority retainer',{id:q.id,proposal:q});return q;
 }
 function clientQuote(l:any){gate(l.id);let q=store.list('QuoteVersion',l.id).find(q=>q.status!=='revised pending approval');if(!q){const r=store.list('RequirementAnswer',l.id)[0]?.value;if(!r)throw new Error('Complete discovery first.');q=makeQuote(l,r);}return q;}
 function notifyFounder(l:any,type:string,data:any){const dest=demo?'founder@demo.invalid':process.env.FOUNDER_EMAIL||'';store.enqueue('email',dest,{subject:'Aurigin: '+type,text:`${l.name} / ${l.company}\n${JSON.stringify(data)}\nReview securely: ${origin}/admin`},type+':'+(data.id||uid()));if(process.env.FOUNDER_WHATSAPP)store.enqueue('whatsapp',demo?'founder-demo':process.env.FOUNDER_WHATSAPP,{text:`Aurigin ${type}. Review securely: ${origin}/admin`},'wa:'+type+':'+(data.id||uid()));}
 function track(type:string,id:string,data:any={}){store.event(type,id,data);store.put('IntegrationSync',{status:'queued',type},id);}
 function blockers(){const integrations=integrationStatus();return[...(!origin.startsWith('https:')?['HTTPS origin required']:[]),...(!process.env.PRIVACY_URL||!process.env.TERMS_URL||!process.env.CONTACT_EMAIL?['Reviewed privacy, terms and contact required']:[]),...(!Object.values(integrations).filter((_,i)=>i<2).every((x:any)=>x.configured)?['Calendar and email credentials required']:[]),...(!store.list('IntegrationCheck').some(x=>x.success&&Date.now()-Date.parse(x.created_at)<86400000)?['Successful adapter checks required']:[]),...(!catalogue().value.services.some((x:any)=>x.status==='approved-live')?['Approved live catalogue scope required']:[])];}
 mountKnowledge(app,store,session);
 mountArko(app,store,{mode,policy,blockers,issue,session,model:options.arkoModel});
 app.get('/api/config',async(req,res)=>{let geo:any={country:null,source:'unconfigured'};try{if(!demo)geo=await geoSuggest(req.socket.remoteAddress||'');}catch{}res.json({mode,productName:policy().productName,services:publicServices,questions,geolocation:geo,privacy:process.env.PRIVACY_URL||'/privacy',terms:process.env.TERMS_URL||'/terms',contact:process.env.CONTACT_EMAIL||null});});
 app.post('/api/register',(req,res)=>{if(!demo&&blockers().length)return res.status(503).json({error:'Live registration awaits configuration review.'});const input=registration.parse(req.body);if(demo&&!input.email.endsWith('.invalid'))return res.status(400).json({error:'Use a synthetic .invalid email in this demo.'});const l=store.put('Lead',{...input,stage:'registered',marketReview:!currencies[input.country]});store.put('Company',{name:l.company,country:l.country},l.id);store.put('ContactPermission',{service:l.contactPermission,marketing:l.marketingPermission,at:now()},l.id);store.put('Attribution',l.attribution,l.id);store.put('MarketAssignment',{country:l.country,currency:currencies[l.country]||null,source:'company confirmation'},l.id);issue(res,l.id);track('registration_completed',l.id);res.json({id:l.id,name:l.name,company:l.company,country:l.country});});
 app.post('/api/resume/request',(req,res)=>{const email=z.email().parse(req.body.email);const l=store.list('Lead').find(x=>x.email.toLowerCase()===email.toLowerCase());let demoCode;if(l){const code=randomBytes(20).toString('hex');store.put('ResumeChallenge',{tokenHash:hash(code),expires:Date.now()+900000,used:false},l.id);store.enqueue('email',l.email,{subject:'Resume your Aurigin project',text:`Enter this one-time code at ${origin}/quote: ${code}`},'resume:'+uid());if(demo)demoCode=code;}res.json({message:'If a project matches, a one-time code will be sent. Codes expire after 15 minutes.',demoCode});});
 app.post('/api/resume/verify',(req,res)=>{const code=z.string().min(20).max(100).parse(req.body.code);const c=store.list('ResumeChallenge').find(x=>x.tokenHash===hash(code)&&!x.used&&x.expires>Date.now());if(!c)return res.status(403).json({error:'Invalid or expired code.'});store.put('ResumeChallenge',{...c,used:true},c.owner,c.id);issue(res,c.owner);res.json({ok:true});});
 app.post('/api/logout',(req,res)=>{for(const name of ['aurigin_session','aurigin_admin','aurigin_arko']){const token=cookie(req,name);if(token)store.db.prepare('DELETE FROM sessions WHERE token_hash=?').run(hash(token));res.clearCookie(name,{path:'/'});}res.json({ok:true});});
 app.get('/api/me',client,(req:any,res)=>{const l=lead(req);res.json({id:l.id,name:l.name,company:l.company,country:l.country,currency:currencies[l.country]||null,stage:l.stage,requirements:store.list('RequirementAnswer',l.id)[0]?.value||null,bookings:store.db.prepare('SELECT id,start,end,status,meeting FROM bookings WHERE lead=? ORDER BY created_at DESC').all(l.id),unlocked:confirmed(l.id),cases:store.list('NegotiationCase',l.id).map(x=>({id:x.id,status:x.clientStatus||'Request received',updated_at:x.updated_at})),entitlement:store.list('DiscountEntitlement',l.id).map(x=>({status:x.status,bps:x.bps,services:x.services})),benefits:store.list('Benefit',l.id).map(x=>({description:x.description,expires:x.expires,status:Date.parse(x.expires)<Date.now()?'expired':x.status}))});});
 app.post('/api/requirements',client,(req:any,res)=>{const r=requirements.parse(req.body);const l=lead(req);store.put('RequirementAnswer',{value:r},l.id);store.put('Lead',{...l,stage:'scope ready'},l.owner,l.id);track('discovery_completed',l.id);if(confirmed(l.id))makeQuote(l,r);res.json(recommend(r,l.country,policy()));});
 app.get('/api/recommendation',client,(req:any,res)=>{const l=lead(req),r=store.list('RequirementAnswer',l.id)[0]?.value;if(!r)return res.status(409).json({error:'Complete discovery first.'});res.json(recommend(r,l.country,policy()));});
 app.post('/api/market-correction',client,(req:any,res)=>{const country=z.string().min(2).max(60).parse(req.body.country),l=lead(req);store.put('NegotiationCase',{type:'market correction',requestedCountry:country,clientStatus:'Request received',status:'pending',reason:'Company country correction requires founder verification'},l.id);notifyFounder(l,'market correction',{id:uid(),country});res.json({message:'Country correction requested. Your current estimate remains unchanged until reviewed.'});});
 app.post('/api/audit',client,async(req:any,res)=>{const l=lead(req);const previous=store.list('AuditRun',l.id)[0];if(previous&&Date.now()-Date.parse(previous.created_at)<3600000)return res.json(previous.result);let result;try{result=await audit(l.website);}catch{result={status:'limited',findings:[],nextStep:'Automated checks could not safely reach the site. Continue with manual questions.'};}const run=store.put('AuditRun',{result},l.id);for(const f of result.findings)store.put('AuditFinding',{...f,run:run.id},l.id);track('audit_completed',l.id);res.json(result);});
 app.post('/api/audit/confirm',client,(req:any,res)=>{store.event('audit_findings_confirmed',req.identity.owner);res.json({ok:true,message:'Noted for consultation; scope will only change through discovery.'});});
 app.get('/api/availability',client,async(_req,res)=>res.json({timezone:policy().timezone,slots:await booking.available(),reservedMinutes:policy().slotMinutes,bufferMinutes:policy().bufferMinutes,demo}));
 app.post('/api/booking',client,async(req:any,res)=>{const b=z.object({start:z.string().datetime(),idempotencyKey:z.string().min(8).max(100)}).strict().parse(req.body);const l=lead(req);track('booking_started',l.id);const result=await booking.book(l.id,b.start,l.email,b.idempotencyKey);res.json({booking:result,demo});});
 app.post('/api/booking/cancel',client,async(req:any,res)=>{await booking.cancel(req.identity.owner,z.string().uuid().parse(req.body.id));res.json({message:'Cancelled. Please choose another appointment; consultation is still required before work starts.'});});
 app.post('/api/waitlist',client,(req:any,res)=>{const l=lead(req);const c=store.put('NegotiationCase',{type:'scheduling',status:'pending',clientStatus:'Request received'},l.id);notifyFounder(l,'scheduling request',c);res.json({message:'Scheduling request received. Expected response within 24 hours; this is not a confirmed booking.'});});
 app.get('/api/quote',client,(req:any,res)=>{const l=lead(req),q=clientQuote(l);if(!q.currency)return res.json({status:'market review',message:'Arjun will confirm the contracting market and currency.'});track('quote_unlocked',l.id);res.json(publicQ(q,l));});
 app.get('/api/proposal.pdf',client,async(req:any,res)=>{const l=lead(req);gate(l.id);const q=req.query.version?store.get(String(req.query.version),'QuoteVersion'):clientQuote(l);if(!q||q.owner!==l.id||q.status==='revised pending approval')return res.sendStatus(404);if(!q.currency)return res.status(409).json({error:'Market review is needed.'});const data=await pdf(publicQ(q,l));store.put('ProposalArtifact',{quote:q.id,hash:q.contentHash,format:'pdf'},l.id);track('proposal_downloaded',l.id);res.type('pdf').set('Content-Disposition','attachment; filename="Aurigin-proposal.pdf"').send(data);});
 app.post('/api/accept',client,(req:any,res)=>{const l=lead(req);gate(l.id);const q=store.get(z.string().uuid().parse(req.body.id),'QuoteVersion');if(!q||q.owner!==l.id||q.status!=='approved'||q.contentHash!==req.body.hash||Date.parse(q.expires)<Date.now())return res.status(409).json({error:'Only an approved, current and valid proposal can be accepted.'});store.put('ClientAcceptance',{quote:q.id,hash:q.contentHash},l.id);track('client_accepted',l.id);res.json({message:'Acceptance recorded. Payment is a separate step.'});});
 app.post('/api/negotiate',client,(req:any,res)=>{const l=lead(req);clientQuote(l);const r=store.list('RequirementAnswer',l.id)[0].value;const tier=z.enum(['max','medium','low']).parse(req.body.tier||'max');const v=makeQuote(l,r,'custom',0,undefined,'Client selected '+tier+' delivery level',true,tier);track('commercial_level_selected',l.id);res.json(publicQ(v,l));});
 app.post('/api/custom-request',client,(req:any,res)=>{const input=z.object({reason:z.string().min(5).max(4000),desiredFee:z.number().int().nonnegative().nullable().default(null),whatsapp:z.boolean().default(false),type:z.string().max(80).default('custom')}).strict().parse(req.body);const l=lead(req);const c=store.put('NegotiationCase',{...input,quote:latestQ(l.id)?.id||null,status:'pending',clientStatus:'Request received'},l.id);notifyFounder(l,'custom request',{...c,proposal:latestQ(l.id)});track('custom_request',l.id);res.json({id:c.id,message:'Request received. Expect a response within 24 hours. You can continue booking while review is pending.'});});
 app.post('/api/ai',client,async(req:any,res)=>{const l=lead(req);if(demo)return res.status(503).json({error:'Live AI is not connected in this demo. Guided recommendations remain available.'});if(store.list('AICall',l.id).length>=8)return res.status(429).json({error:'AI guidance limit reached. Please continue guided discovery.'});const r=store.list('RequirementAnswer',l.id)[0]?.value||{};store.put('AICall',{status:'requested',model:process.env.OPENAI_MODEL},l.id);const result=await aiGuidance({recommendation:recommend(r,l.country,policy()).services.map(s=>({id:s.id,name:s.name,why:s.why})),question:z.string().max(1000).parse(req.body.question)});const v=z.object({explanation:z.string().max(3000),followUp:z.string().max(1000)}).strict().parse(result);if(/\d|₹|\$|£|AED|INR|GBP|USD|percent|price|fee/i.test(v.explanation+v.followUp))return res.json({explanation:'Please review the recommended scope. Commercial questions are handled in your authorized estimate after booking.',followUp:''});res.json(v);});
 app.post('/api/admin/login',(req,res)=>{const password=z.string().max(200).parse(req.body.password);if(!timingSafeEqual(scryptSync(password,adminSalt,64),adminHash))return res.status(403).json({error:'Invalid founder credentials.'});issue(res,'founder','admin');store.event('admin_login','founder');res.json({ok:true});});
 app.get('/api/admin/dashboard',admin,(_req,res)=>{res.json({mode,leads:store.list('Lead'),bookings:store.db.prepare('SELECT * FROM bookings ORDER BY start').all(),quotes:store.list('QuoteVersion'),cases:store.list('NegotiationCase'),payments:store.list('PaymentRecord'),entitlements:store.list('DiscountEntitlement'),benefits:store.list('Benefit'),referrals:store.list('Referral'),rewards:store.list('Reward'),outbox:store.db.prepare('SELECT * FROM outbox ORDER BY created_at DESC LIMIT 100').all(),sync:store.list('IntegrationSync'),policy:policy(),catalogue:catalogue(),conflicts:reconcile(catalogue().value,policy()),integrations:integrationStatus(),liveBlockers:blockers(),events:store.list('AuditEvent').slice(0,100),policyVersion:store.list('Policy')[0].id});});
 app.get('/api/admin/preview/:id',admin,(req,res)=>{const q=store.get(req.params.id,'QuoteVersion');if(!q)return res.sendStatus(404);const l=store.get(q.owner,'Lead');res.json({proposal:publicQ(q,l),internal:q});});
 app.post('/api/admin/policy',admin,(req,res)=>{const value=policySchema.parse(req.body.value);const reason=z.string().min(5).max(1000).parse(req.body.reason);if(value.benefitEnabled&&(!value.benefitCost||!value.benefitHours))throw new Error('A benefit needs cost and a bounded allowance');const saved=store.put('Policy',{value,reason,status:'admin configured'});store.event('policy_version_published','founder',{id:saved.id,reason});res.json({ok:true});});
 app.post('/api/admin/catalogue/preview',admin,(req,res)=>{const values=z.array(z.object({id:z.string(),standard:z.number().int().positive(),floor:z.number().int().positive().nullable(),cost:z.number().int().nonnegative().nullable(),status:z.enum(['draft','demo-ready','approved-live','suspended']),scope:z.object({deliverables:z.array(z.string()).min(1),supplies:z.array(z.string()),exclusions:z.array(z.string()),timeline:z.string(),hours:z.array(z.number()).optional(),caps:z.record(z.string(),z.number()).optional()}),reviewNote:z.string().max(4000)}).strict()).parse(req.body.changes);const value=structuredClone(catalogue().value);for(const x of values){const row=value.services.find((s:any)=>s.id===x.id);if(!row)throw new Error('Unknown service');Object.assign(row,x);if(x.status==='approved-live'){if(!x.reviewNote||x.cost===null||x.floor===null)throw new Error('Documented cost and scope review required');const result=calculate([{...row,original:row.standard,quantity:1,eligible:true}],row.market,policy());if(result.economicStatus!=='validated')throw new Error('Continuing promotion fails economics');row.scopeStatus='approved';}}const draft=store.put('CatalogueDraft',{value,base:catalogue().id});res.json({draftId:draft.id,conflicts:reconcile(value,policy()),affected:store.list('QuoteVersion').filter(q=>q.status!=='approved').map(q=>q.id),note:'Accepted agreements remain unchanged.'});});
 app.post('/api/admin/catalogue/publish',admin,(req,res)=>{const d=store.get(req.body.draftId,'CatalogueDraft');if(!d||d.base!==catalogue().id)throw new Error('Stale catalogue preview');const reason=z.string().min(5).parse(req.body.reason);const v=store.put('CatalogueVersion',{value:d.value,reason});store.event('catalogue_published','founder',{id:v.id});res.json({ok:true});});
 app.post('/api/admin/revise',admin,(req,res)=>{const input=z.object({quoteId:z.string().uuid(),reason:z.string().min(5),lines:z.array(z.object({service:z.string(),name:z.string().min(1),original:z.number().int().nonnegative(),cadence:z.enum(['monthly','project']),eligible:z.boolean(),floor:z.number().int().nonnegative().nullable(),cost:z.number().int().nonnegative().nullable(),scope:z.object({deliverables:z.array(z.string()).min(1),supplies:z.array(z.string()),exclusions:z.array(z.string()),timeline:z.string()})})).min(1),route:z.enum(['promotion','custom']).default('promotion')}).strict().parse(req.body);const old=store.get(input.quoteId,'QuoteVersion');if(!old)throw new Error('Proposal not found');const l=store.get(old.owner,'Lead');gate(l.id);const q=makeQuote(l,old.requirements,input.route,0,input.lines.map(x=>({...x,quantity:1,maxQuantity:1,unit:'agreed scope'})),input.reason);const a=store.put('ApprovalRequest',{quote:q.id,hash:q.contentHash,expires:Date.now()+86400000,status:'pending'},l.id);res.json({proposal:publicQ(q,l),approvalId:a.id});});
 app.post('/api/admin/approve',admin,(req,res)=>{const input=z.object({quoteId:z.string().uuid(),hash:z.string(),acknowledge:z.literal(true),override:z.boolean().default(false),reason:z.string().min(5)}).strict().parse(req.body);const q=store.get(input.quoteId,'QuoteVersion');if(!q||q.contentHash!==input.hash||latestQ(q.owner)?.id!==q.id) return res.status(409).json({error:'This proposal version is stale. Review the latest exact preview.'});if(q.pricing.lines.some((line:any)=>{const band=q.market==='IN'?launchPrices.find(x=>x[0]===line.service):null;const floor=Math.max(line.floor||0,band?band[5]*100:0);return line.converted<floor;}))return res.status(409).json({error:'This proposal is below the service floor. Create a compliant revision before approval.'});const prev=store.list('ApprovalDecision',q.owner).find(a=>a.quote===q.id);if(prev)return res.json({ok:true,duplicate:true});if(Date.parse(q.expires)<Date.now())throw new Error('Proposal expired');if(q.pricing.economicStatus!=='validated'&&!input.override)throw new Error('Economics require a deliberate founder override with a reason.');if(!demo&&(q.pricing.economicStatus!=='validated'||q.reviewReasons.some((s:string)=>s.includes('commercial_review'))))throw new Error('Live commercial readiness must be resolved before approval.');store.tx(()=>{store.put('ApprovalDecision',{quote:q.id,hash:q.contentHash,reason:input.reason,override:input.override},q.owner);store.put('QuoteVersion',{...q,status:'approved'},q.owner,q.id);const l=store.get(q.owner,'Lead');store.enqueue('email',l.email,{subject:'Your revised Aurigin proposal is ready',text:`Proposal ${q.id} version ${q.number} is approved. Open ${origin}/quote and resume securely to review it.`},'approved:'+q.id);store.event('final_proposal_approved',q.owner,{quote:q.id});for(const c of store.list('NegotiationCase',q.owner).filter(c=>c.status==='pending'))store.put('NegotiationCase',{...c,status:'approved',clientStatus:'Revised proposal ready'},c.owner,c.id);});res.json({ok:true});});
 app.post('/api/admin/case',admin,(req,res)=>{const input=z.object({id:z.string().uuid(),action:z.enum(['review','reject','call','information','attended','missed','market']),note:z.string().min(3).max(2000),country:z.string().optional()}).parse(req.body);const c=store.get(input.id,'NegotiationCase');if(!c)throw new Error('Case missing');const status={review:'Under agency review',reject:'Please discuss with Aurigin',call:'Please discuss with Aurigin',information:'Please discuss with Aurigin',attended:'Under agency review',missed:'Please discuss with Aurigin',market:'Proposal being updated'}[input.action];store.put('NegotiationCase',{...c,clientStatus:status,status:input.action==='reject'?'rejected':'pending',founderNote:input.note},c.owner,c.id);if(input.action==='market'){if(!input.country)throw new Error('Country required');const l=store.get(c.owner,'Lead');store.put('Lead',{...l,country:input.country},l.owner,l.id);store.put('MarketAssignment',{country:input.country,source:'founder approved correction'},l.id);const r=store.list('RequirementAnswer',l.id)[0]?.value;if(r&&confirmed(l.id))makeQuote({...l,country:input.country},r);}track('case_'+input.action,c.owner);res.json({ok:true});});
 app.post('/api/admin/payment',admin,(req,res)=>{const input=z.object({quoteId:z.string().uuid(),reference:z.string().min(3).max(100),amount:z.number().int().positive(),status:z.enum(['received','refunded','voided']).default('received')}).strict().parse(req.body);const q=store.get(input.quoteId,'QuoteVersion');if(!q||q.status!=='approved')throw new Error('An approved proposal is required.');const once='payment:'+input.status+':'+input.reference;if(store.db.prepare('SELECT * FROM once_keys WHERE key=?').get(once))return res.json({duplicate:true});store.tx(()=>{const pay=store.put('PaymentRecord',{...input,verifiedBy:'founder',verifiedAt:now()},q.owner);store.db.prepare('INSERT INTO once_keys VALUES(?,?)').run(once,pay.id);if(input.status==='received'){if(!store.list('DiscountEntitlement',q.owner).length&&q.pricing.route==='promotion')store.put('DiscountEntitlement',{bps:q.promotionBps||1600,status:'active',services:q.pricing.lines.filter((x:any)=>x.eligible!==false).map((x:any)=>x.service),acceptedQuote:q.id,start:now(),end:null,renewalPolicy:policy().reactivationPolicy},q.owner);const p=policy();if(q.benefitSnapshot&&!store.list('Benefit',q.owner).length)store.put('Benefit',{description:q.benefits,status:'active',start:now(),expires:new Date(Date.now()+q.benefitSnapshot.days*86400000).toISOString(),quote:q.id},q.owner);for(const r of store.list('Referral',q.owner)){if(!store.list('Reward',r.id).length)store.put('Reward',{status:'review',payment:pay.id,ruleVersion:store.list('Policy')[0].id,amount:p.referralReward,issuedAt:null},r.id);}track('first_payment_verified',q.owner);}else{store.put('PaymentReview',{payment:pay.id,reason:input.status,status:'pending'},q.owner);} });res.json({ok:true});});
 app.post('/api/referral',client,(req:any,res)=>{const l=lead(req),referrer=z.string().uuid().parse(req.body.referrer);if(referrer===l.id||!store.get(referrer,'Lead')||store.get(referrer,'Lead')?.email?.toLowerCase()===l.email.toLowerCase()||store.list('Referral',l.id).length)throw new Error('Invalid or duplicate referral');store.put('Referral',{referrer,referred:l.id,attributionDate:now(),state:'awaiting first payment',ruleVersion:store.list('Policy')[0].id},l.id);res.json({ok:true,message:'Referral attribution recorded; rewards require paid conversion and review.'});});
 app.get('/api/admin/export',admin,(_req,res)=>{res.set('Content-Disposition','attachment; filename="aurigin-crm-export.json"').json({exportedAt:now(),leads:store.list('Lead'),quotes:store.list('QuoteVersion').map(q=>({id:q.id,owner:q.owner,status:q.status,market:q.market,currency:q.currency,created_at:q.created_at})),bookings:store.db.prepare('SELECT * FROM bookings').all(),referrals:store.list('Referral')});});
 async function work(){const pending=store.db.prepare("SELECT * FROM outbox WHERE status IN ('queued','failed') AND next_attempt<=? AND attempts<5").all(Date.now()) as any[];for(const item of pending){try{let result;if(demo)result={demo:true};else if(item.channel==='email')result=await sendEmail(item.destination,JSON.parse(item.payload),item.dedupe);else if(item.channel==='whatsapp')result=await sendWhatsApp(item.destination,JSON.parse(item.payload));else throw new Error('Unknown channel');store.db.prepare('UPDATE outbox SET status=?,attempts=attempts+1,last_error=NULL WHERE id=?').run(demo?'demo recorded':'sent',item.id);store.put('DeliveryAttempt',{outbox:item.id,status:demo?'demo recorded':'sent',providerId:result?.id||null});}catch{store.db.prepare("UPDATE outbox SET status='failed',attempts=attempts+1,last_error=?,next_attempt=? WHERE id=?").run('Provider unavailable; verify configuration',Date.now()+Math.min(3600000,30000*2**item.attempts),item.id);}}
 for(const c of store.list('NegotiationCase').filter(c=>c.status==='pending'&&Date.now()-Date.parse(c.created_at)>86400000)){const l=store.get(c.owner,'Lead');store.enqueue('email',demo?'founder@demo.invalid':process.env.FOUNDER_EMAIL||'',{subject:'Aurigin review overdue',text:`Case ${c.id} for ${l.company} remains under review.`},'overdue:'+c.id);}
 }
 app.post('/api/admin/retry',admin,async(req,res)=>{if(req.body.id)store.db.prepare("UPDATE outbox SET status='queued',attempts=0,next_attempt=0 WHERE id=? AND status='failed'").run(req.body.id);await work();res.json({ok:true});});
 app.post('/api/admin/sync',admin,async(_req,res)=>{const rows=[['ID','Company','Market','Stage','Updated'],...store.list('Lead').map(l=>[l.id,l.company,l.country,l.stage,l.updated_at]),['BOOKINGS'],...((store.db.prepare('SELECT * FROM bookings').all()) as any[]).map(b=>[b.id,b.lead,b.start,b.status]),['QUOTES'],...store.list('QuoteVersion').map(q=>[q.id,q.owner,q.market,q.status,q.updated_at]),['CONVERSIONS'],...store.list('PaymentRecord').map(p=>[p.id,p.owner,p.status,p.updated_at]),['REFERRALS'],...store.list('Referral').map(r=>[r.id,r.owner,r.state,r.updated_at])];try{if(!demo)await syncSheet(rows);store.put('IntegrationSync',{status:demo?'demo recorded':'synced',at:now()});res.json({ok:true,demo});}catch{store.put('IntegrationSync',{status:'failed',at:now()});res.status(503).json({error:'Sheets sync failed; authoritative records are safe. Retry from admin.'});}});
 app.post('/api/admin/check-integrations',admin,async(_req,res)=>{if(demo)return res.json({success:false,message:'Demo adapters only. No live credentials were exercised.'});try{const checks=await checkConnections();const success=checks.calendar.success&&checks.email.success;store.put('IntegrationCheck',{success,checks,at:now()});res.json({success,checks,note:'Read-only provider checks completed. Real delivery and meeting creation still need owner-authorized activation tests.'});}catch{res.status(503).json({error:'Calendar integration check failed.'});}});
 app.get('/api/callbacks/whatsapp',(req,res)=>{if(!demo&&process.env.WHATSAPP_VERIFY_TOKEN&&req.query['hub.mode']==='subscribe'&&req.query['hub.verify_token']===process.env.WHATSAPP_VERIFY_TOKEN)return res.type('text').send(String(req.query['hub.challenge']||''));res.sendStatus(403);});
 app.post('/api/callbacks/whatsapp',(req:any,res)=>{if(demo||!process.env.WHATSAPP_APP_SECRET||!verifySignature(req.rawBody,req.get('x-hub-signature-256')||'',process.env.WHATSAPP_APP_SECRET))return res.sendStatus(403);store.event('whatsapp_verified_callback',null,{digest:hash(req.rawBody.toString())});res.json({received:true});});

 app.post('/api/draft',client,(req:any,res)=>{const r=requirements.parse(req.body);store.put('DiscoveryDraft',{value:r},req.identity.owner,'draft-'+req.identity.owner);res.json({savedAt:now()});});
 app.get('/api/draft',client,(req:any,res)=>res.json({value:store.list('DiscoveryDraft',req.identity.owner)[0]?.value||null}));
 app.get('/api/options',client,(req:any,res)=>{const l=lead(req);const r=store.list('RequirementAnswer',l.id)[0]?.value;if(!r)throw new Error('Complete discovery first');const options=alternatives(r).slice(0,3).map(a=>{const recommendation=recommend(a.requirements,l.country,policy());const q=confirmed(l.id)&&currencies[l.country]?makeQuote(l,a.requirements,'promotion',0,undefined,'Comparison only',false):null;return{id:a.id,name:a.name,services:recommendation.services,reasons:recommendation.reasons,...(q?{currency:q.currency,pricing:publicPricing(q.pricing)}:{})};});res.json({options,unlocked:confirmed(l.id),message:'Select a scope to save a new version. Prices stay locked until booking.'});});
 app.post('/api/options/select',client,(req:any,res)=>{const l=lead(req),r=store.list('RequirementAnswer',l.id)[0]?.value;const option=alternatives(r).find(a=>a.id===req.body.id);if(!option)throw new Error('Unknown option');store.put('RequirementAnswer',{value:option.requirements},l.id);if(confirmed(l.id))makeQuote(l,option.requirements);res.json(recommend(option.requirements,l.country,policy()));});
 app.post('/api/admin/reconcile-booking',admin,async(req,res)=>{const b=store.db.prepare('SELECT * FROM bookings WHERE id=?').get(z.string().uuid().parse(req.body.id)) as any;if(!b)throw new Error('Booking missing');res.json(await booking.reconcile(b.id,store.get(b.lead,'Lead').email));});
 app.post('/api/admin/attendance',admin,(req,res)=>{const v=z.object({id:z.string().uuid(),status:z.enum(['attended','missed'])}).parse(req.body);const b=store.db.prepare("SELECT * FROM bookings WHERE id=? AND status='confirmed'").get(v.id) as any;if(!b)throw new Error('Confirmed booking required');store.put('ConsultationAttendance',{booking:v.id,status:v.status},b.lead);track('consultation_'+v.status,b.lead);res.json({ok:true});});
 app.post('/api/admin/reward',admin,(req,res)=>{const v=z.object({id:z.string().uuid(),reference:z.string().min(3),reason:z.string().min(5)}).parse(req.body);const reward=store.get(v.id,'Reward');if(!reward||reward.status!=='review')throw new Error('No pending reward');const p=policy();if(p.referralReward===null||p.referralCap===null)throw new Error('Configure reward value and cap before issuing');const referral=store.get(reward.owner,'Referral');if(!referral)throw new Error('Referral missing');const paid=store.get(reward.payment,'PaymentRecord');if(!paid||paid.status!=='received')throw new Error('Verified payment required');const issued=store.list('Reward').filter(x=>x.status==='issued'&&store.get(x.owner,'Referral')?.referrer===referral.referrer);if(issued.reduce((n,x)=>n+x.amount,0)+p.referralReward>p.referralCap)throw new Error('Referral reward cap reached');store.put('Reward',{...reward,status:'issued',amount:p.referralReward,reference:v.reference,reason:v.reason,issuedAt:now()},reward.owner,reward.id);store.event('reward_issued','founder',{reward:reward.id});res.json({ok:true,message:'Manual reward issuance recorded. No payment was sent by this application.'});});
 app.post('/api/admin/association',admin,(req,res)=>{const v=z.object({leadId:z.string().uuid(),action:z.enum(['cancel','reactivate','review']),reason:z.string().min(5)}).parse(req.body);const e=store.list('DiscountEntitlement',v.leadId)[0];if(!e)throw new Error('Entitlement missing');store.put('DiscountEntitlement',{...e,status:v.action==='cancel'?'terminated':v.action==='reactivate'?'active':'review',reviewReason:v.reason},v.leadId,e.id);store.event('association_'+v.action,v.leadId,{reason:v.reason});res.json({ok:true});});
 app.post('/api/admin/planning-range',admin,(req,res)=>{const v=z.object({leadId:z.string().uuid(),service:z.string(),lower:z.number().int().nonnegative(),upper:z.number().int().positive(),cadence:z.enum(['project','monthly']),scope:z.string().min(15).max(4000),reason:z.string().min(5)}).strict().parse(req.body);if(v.upper<v.lower||!publicServices.some(s=>s.id===v.service))throw new Error('Invalid range or service');const l=store.get(v.leadId,'Lead');if(!l||!currencies[l.country])throw new Error('Supported market required');const range=store.put('PlanningRange',{...v,currency:currencies[l.country],status:'pending',expires:Date.now()+policy().validityDays*86400000,hash:hash(v)},l.id);res.json(range);});
 app.post('/api/admin/planning-range/approve',admin,(req,res)=>{const v=z.object({id:z.string().uuid(),hash:z.string(),acknowledge:z.literal(true)}).parse(req.body);const r=store.get(v.id,'PlanningRange');if(!r||r.hash!==v.hash||r.expires<Date.now())throw new Error('Stale range approval');store.put('PlanningRange',{...r,status:'approved'},r.owner,r.id);store.event('planning_range_approved',r.owner,{id:r.id,hash:r.hash});res.json({ok:true});});
 app.get('/api/planning-ranges',client,(req:any,res)=>{gate(req.identity.owner);res.json({ranges:store.list('PlanningRange',req.identity.owner).filter(r=>r.status==='approved'&&r.expires>Date.now()).map(r=>({id:r.id,service:r.service,lower:r.lower,upper:r.upper,currency:r.currency,scope:r.scope,cadence:r.cadence,expires:r.expires,qualification:'Founder-approved planning range only; capability, partner costs and final scope require discovery.'}))});});
 app.post('/api/events',(req,res)=>{const v=z.object({type:z.enum(['registration_started','discovery_started','audit_requested','booking_gate_reached','scope_option_compared']),source:z.string().max(100).optional()}).strict().parse(req.body);const owner=session(req)?.owner||null;store.event(v.type,owner,{source:v.source||'planner'});res.json({ok:true});});
 app.use('/api',(_req,res)=>res.status(404).json({error:'Endpoint not found.'}));
 app.use((err:any,_req:any,res:any,_next:any)=>{res.status(err.status||((err instanceof z.ZodError)?400:409)).json({error:err instanceof z.ZodError?'Please check your answers. '+err.issues.map((x:any)=>x.path.join('.')+': '+x.message).join('; '):String(err.message||'Unable to complete this action.').slice(0,700)});});
 return{app,store,booking,work,policy,catalogue};
}
