import dns from 'node:dns/promises';
import https from 'node:https';
import ipaddr from 'ipaddr.js';
export function publicIP(address:string){try{return ipaddr.process(address).range()==='unicast';}catch{return false;}}
export async function safeHTML(raw:string,depth=0):Promise<{html:string,url:string}>{
 if(depth>3)throw new Error('Too many redirects');const u=new URL(raw);if(u.protocol!=='https:'||u.username||u.password||(u.port&&u.port!=='443'))throw new Error('Only public HTTPS websites are supported');const host=u.hostname.replace(/^\[|\]$/g,'');const addresses=await dns.lookup(host,{all:true});if(!addresses.length||addresses.some(x=>!publicIP(x.address)))throw new Error('Private or reserved destinations are blocked');
 return new Promise((resolve,reject)=>{const pinned=addresses[0];const request=https.get(u,{timeout:7000,headers:{'User-Agent':'AuriginDiagnostic/1.0','Accept':'text/html,text/plain'},lookup:((_h:any,_o:any,cb:any)=>cb(null,pinned.address,pinned.family)) as any},res=>{if(res.statusCode&&res.statusCode>=300&&res.statusCode<400&&res.headers.location){res.resume();safeHTML(new URL(res.headers.location,u).toString(),depth+1).then(resolve,reject);return;}if(res.statusCode!==200){res.resume();reject(new Error('Website is unavailable'));return;}if(!/text\/(html|plain)/i.test(res.headers['content-type']||'')){res.resume();reject(new Error('Only HTML or robots text is supported'));return;}let size=0,parts:Buffer[]=[];res.on('data',c=>{size+=c.length;if(size>300000){request.destroy(new Error('Content size limit reached'));return;}parts.push(c);});res.on('end',()=>resolve({url:u.toString(),html:Buffer.concat(parts).toString('utf8')}));});request.on('timeout',()=>request.destroy(new Error('Website timed out')));request.on('error',reject);});
}
export async function audit(url:string){const date=new Date().toISOString();if(!url)return{status:'manual',findings:[{title:'Plan your project proof',observation:'No website was supplied. Share 3 representative projects during consultation.',source:'user',confidence:'high',date,url:null},{title:'Define an enquiry route',observation:'Confirm who should receive and follow up new enquiries.',source:'user question',confidence:'unconfirmed',date,url:null},{title:'Choose an approval owner',observation:'Confirm who can supply and approve the launch material.',source:'user question',confidence:'unconfirmed',date,url:null}],nextStep:'A scoped portfolio or launch discovery conversation.'};
 const origin=new URL(url).origin;let robots;try{robots=await safeHTML(origin+'/robots.txt');}catch{return{status:'limited',findings:[],nextStep:'Robots access could not be verified. Share your website goals for a manual diagnostic.'};}
 const path=new URL(url).pathname;let relevant=false;for(const raw of robots.html.split('\n')){const line=raw.split('#')[0].trim();if(/^user-agent:/i.test(line))relevant=/\*|AuriginDiagnostic/i.test(line);if(relevant&&/^disallow:/i.test(line)){const rule=line.split(':').slice(1).join(':').trim();if(rule&&(path.startsWith(rule)||rule.includes('*')))return{status:'limited',findings:[],nextStep:'Automated review is restricted by this website. Continue with manual questions.'};}}
 const page=await safeHTML(url);const html=page.html.replace(/<(script|style)[\s\S]*?<\/\1>/gi,'');const checks=[['Website clarity',/<title>[^<]{3,}<\/title>/i.test(html),'A page title is present. Confirm that it describes your service and audience.','A descriptive page title was not detected. Check the rendered page before changing it.'],['Portfolio proof',/project|portfolio|case stud/i.test(html),'Project or portfolio language is visible. Review whether the examples provide enough context.','Project proof was not detected in the fetched HTML. It may be loaded dynamically; please confirm.'],['Enquiry route',/contact|mailto:|<form/i.test(html),'An enquiry or contact route is visible. Confirm the owner and follow-up process.','A contact route was not detected in the fetched HTML. Confirm manually before adding scope.']];
 return{status:'completed',pagesFetched:1,findings:checks.map(([title,ok,yes,no])=>({title,observation:ok?yes:no,url:page.url,date,source:'deterministic HTML check',confidence:'medium',confirmed:false})),nextStep:'Review project proof and enquiry flow in a focused website scope. No analytics, advertising results or revenue were assessed.'};
}
