import { DateTime } from 'luxon';
import { Store,uid,now } from './store.ts';
import type { CalendarAdapter,Interval } from './adapters.ts';
import type { Policy } from './policy.ts';
export const overlaps=(a:Interval,b:Interval)=>Date.parse(a.start)<Date.parse(b.end)&&Date.parse(a.end)>Date.parse(b.start);
export function slots(p:Policy,busy:Interval[],records:any[],clock=Date.now()){
 const result:any[]=[];const today=DateTime.fromMillis(clock,{zone:p.timezone}).startOf('day');
 for(let d=0;d<p.horizonDays;d++){const day=today.plus({days:d});const date=day.toISODate()!;if(day.weekday>5||p.blackouts.includes(date))continue;const active=records.filter(r=>r.local_day===date&&['confirmed','held','pending'].includes(r.status));if(active.length>=p.dailyCap)continue;const [sh,sm]=p.workStart.split(':').map(Number),[eh,em]=p.workEnd.split(':').map(Number);const close=day.set({hour:eh,minute:em});
 for(let t=day.set({hour:sh,minute:sm});t.plus({minutes:p.slotMinutes+p.bufferMinutes})<=close;t=t.plus({minutes:15})){const start=t.toUTC().toISO()!,end=t.plus({minutes:p.slotMinutes}).toUTC().toISO()!,reservedEnd=t.plus({minutes:p.slotMinutes+p.bufferMinutes}).toUTC().toISO()!;if(t.toMillis()<clock+p.noticeHours*3600000)continue;const interval={start,end:reservedEnd};if([...busy,...p.blocks,...active.map(r=>({start:r.start,end:r.reserved_end}))].some(b=>overlaps(interval,b)))continue;result.push({start,end,reservedEnd,localDay:date,founderTimezone:p.timezone});}}
 return result;
}
export class BookingService {
 constructor(public store:Store,public adapter:CalendarAdapter,public policy:()=>Policy){}
 records(){return this.store.db.prepare("SELECT * FROM bookings WHERE status IN ('held','confirmed','pending')").all() as any[];}
 async available(){const p=this.policy();const start=now(),end=new Date(Date.now()+p.horizonDays*86400000).toISOString();return slots(p,await this.adapter.busy(start,end),this.records());}
 async book(lead:string,start:string,email:string,key:string){const idem=lead+':'+key;const previous=this.store.db.prepare('SELECT * FROM bookings WHERE idempotency=?').get(idem) as any;if(previous)return previous;const found=(await this.available()).find(s=>s.start===start);if(!found)throw new Error('That time is no longer available. Please choose another.');const id=uid();const p=this.policy();this.store.tx(()=>{const active=this.records();if(active.filter(x=>x.local_day===found.localDay).length>=p.dailyCap||active.some(x=>overlaps({start:found.start,end:found.reservedEnd},{start:x.start,end:x.reserved_end})))throw new Error('This appointment was just reserved. Choose another time.');if(active.some(x=>x.lead===lead))throw new Error('You already have an active appointment. Cancel it before choosing a new time.');this.store.db.prepare('INSERT INTO bookings VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,lead,start,found.end,found.reservedEnd,found.localDay,'held',null,null,idem,Date.now()+120000,now());});
 try{const event=await this.adapter.reserve(id,start,found.end,found.reservedEnd,email);if(!event.confirmed)throw new Error('Provider confirmation pending');try{this.store.db.prepare("UPDATE bookings SET status='confirmed',event_id=?,meeting=?,expires=NULL WHERE id=?").run(event.id,event.meeting,id);}catch(e){try{await this.adapter.cancel(event.id);}catch{this.store.db.prepare("UPDATE bookings SET status='pending',event_id=? WHERE id=?").run(event.id,id);}throw e;}this.store.event('booking_confirmed',lead,{id});return this.store.db.prepare('SELECT * FROM bookings WHERE id=?').get(id);}catch(e){this.store.db.prepare("UPDATE bookings SET status='pending' WHERE id=? AND status='held'").run(id);this.store.event('booking_reconciliation_required',lead,{id});throw new Error('Booking confirmation is pending reconciliation. No price has been unlocked.');}
 }
 async cancel(lead:string,id:string){const b=this.store.db.prepare('SELECT * FROM bookings WHERE id=? AND lead=?').get(id,lead) as any;if(!b||b.status!=='confirmed')throw new Error('Confirmed booking not found');await this.adapter.cancel(b.event_id);this.store.db.prepare("UPDATE bookings SET status='cancelled' WHERE id=?").run(id);this.store.event('booking_cancelled',lead,{id});}
 async reconcile(id:string,email:string){const b=this.store.db.prepare("SELECT * FROM bookings WHERE id=? AND status IN ('held','pending')").get(id) as any;if(!b)throw new Error('No pending hold found');const event=await this.adapter.reserve(b.id,b.start,b.end,b.reserved_end,email);if(!event.confirmed)throw new Error('Provider has not confirmed');this.store.db.prepare("UPDATE bookings SET status='confirmed',event_id=?,meeting=?,expires=NULL WHERE id=?").run(event.id,event.meeting,b.id);this.store.event('booking_confirmed',b.lead,{id:b.id,reconciled:true});return{confirmed:true};}
}
