import seed from './seed.json' with {type:'json'};
export const currencies:Record<string,string>={IN:'INR',AE:'AED',GB:'GBP',US:'USD'};
export const publicServices=[
 ['landing','Landing page','A','A focused destination for one offer.'],['portfolio','Portfolio website','A','Help prospective clients understand your work.'],['business','Business website','A','Organize a larger set of services and projects.'],['ecommerce','Ecommerce','B','Present products with a controlled purchase journey.'],['logo','Logo & visual starter','A','Create a consistent visual starting point.'],['identity','Brand identity','A','Bring your positioning and visual identity together.'],['social','Social & content','B','Build consistency using your project material.'],['seo','Search visibility','B','Improve technical and content foundations.'],['local-seo','Local visibility','B','Help eligible local customers find you.'],['paid-media','Paid campaigns','C','Assess tracking, specialist support and lead handoff.'],['care','Website care','B','Keep a supported website maintained.'],['3d','Video & 3D','C','Review models, assets and production needs.'],['software','Software & portals','D','Start with technical discovery.'],['crm','CRM & workflows','D','Map processes before selecting a platform.'],['ai','AI & automation','D','Assess data, approval points and usage.'],['tele-services','Lead follow-up operations','D','Define qualification, staffing and handoff.'],['creative','Graphic design & reels','B','Define unique assets, formats and revisions.'],['linkedin','LinkedIn programs','C','Confirm proof, specialist and delivery scope.']
].map(([id,name,readiness,why])=>({id,name,readiness,why}));
export const scopes:Record<string,any>={
 landing:{deliverables:['1 landing page, 1 unique template','1 contact form and routing destination','2 consolidated revision rounds','Responsive build and basic tracking'],supplies:['Final copy, brand assets and licensed images'],exclusions:['Hosting, paid licences, original copywriting, custom backend'],timeline:'2–4 weeks',hours:[18,25],caps:{pages:1,templates:1,forms:1,revisions:2}},
 portfolio:{deliverables:['Up to 7 standard pages, 2 unique templates','Up to 6 portfolio projects','1 enquiry form, basic analytics','2 consolidated revision rounds'],supplies:['Copy, project descriptions and licensed images'],exclusions:['Original photography, multilingual content, portals, paid tools'],timeline:'4–6 weeks',hours:[45,65],caps:{pages:7,templates:2,projects:6,forms:1,revisions:2}},
 business:{deliverables:['Up to 15 standard pages, 3 unique templates','Up to 10 portfolio projects','1 CMS collection, 2 forms','3 revision rounds and 2 strategy calls'],supplies:['Approved copy, images and access'],exclusions:['Custom portals, complex migration, unlisted integrations'],timeline:'6–9 weeks',hours:[80,110],caps:{pages:15,templates:3,projects:10,revisions:3}},
 logo:{deliverables:['2 logo directions; one chosen logo suite','Colors, typography and mini guide','2 revision rounds within chosen direction'],supplies:['Business brief and one approval owner'],exclusions:['Naming, trademark clearance, registration and new directions'],timeline:'3–4 weeks',hours:[24,34],caps:{concepts:2,revisions:2}},
 identity:{deliverables:['Positioning workshop, 3 visual directions','Identity suite, guide and stationery','4 social templates; 3 revision rounds'],supplies:['Stakeholder brief and consolidated feedback'],exclusions:['Trademark registration, unlimited concepts, original photography'],timeline:'4–8 weeks',hours:[45,70],caps:{concepts:3,revisions:3,templates:4}},
 social:{deliverables:['10 unique static or carousel assets, up to 7 panels each','4 edited reels, up to 45 seconds, supplied footage','2 platforms with adaptations, captions and scheduling','Community responses capped at 2 hours/month','1 monthly report and 1 meeting'],supplies:['Usable footage and project material, one approval owner'],exclusions:['Shoots, media spend, influencers, unused asset rollover'],timeline:'Monthly; 3-month initial commitment',hours:[28,40],caps:{assets:10,reels:4,panels:7,platforms:2,communityHours:2,meetings:1}},
 seo:{deliverables:['Technical baseline for up to 15 pages','2 articles up to 1,200 words or equivalent page optimization','20 tracked keywords, monthly report and 1 meeting'],supplies:['Analytics and Search Console access; content approval'],exclusions:['Major rebuild, paid placements, ranking or traffic guarantees'],timeline:'6 months recommended',hours:[24,35],caps:{pages:15,articles:2,keywords:20,meetings:1}},
 'local-seo':{deliverables:['1 eligible location and Google Business Profile','5 page optimizations; 10 citation checks','1 monthly report and meeting'],supplies:['Genuine address/eligibility, account access and content'],exclusions:['Fake locations, guaranteed rankings, website rebuild'],timeline:'3-month initial commitment',hours:[18,25],caps:{locations:1,pages:5,citations:10}},
 care:{deliverables:['1 supported website; updates, backups and monitoring','4 support hours/month, 1 monthly report'],supplies:['Hosting ownership, access and known issue list'],exclusions:['Redesign, new features, licences, unlimited support'],timeline:'Monthly; 3-month initial commitment',hours:[6,14],caps:{sites:1,supportHours:4}},
 ecommerce:{deliverables:['Up to 50 products on a supported platform','5 standard page templates, one payment gateway','2 revision rounds and handover'],supplies:['Product data, images, account access and policies'],exclusions:['ERP, custom inventory, large migration and unusual checkout'],timeline:'8–14 weeks',hours:[120,170],caps:{products:50,templates:5,revisions:2}}
};
export function initialCatalogue(){return{...seed,services:seed.services.map(s=>({...s,scope:scopes[s.service]||{deliverables:['Discovery and a founder-approved scope'],supplies:['Relevant systems, assets and constraints'],exclusions:['Execution before readiness review'],timeline:'Confirmed after discovery',hours:[],caps:{}},scopeStatus:'provisional',premiumScope:null}))};}
export function reconcile(cat:any,p:any){return[...cat.services,...cat.packages].map((s:any)=>({id:s.id,name:s.name,market:s.market,status:s.status,issues:[...(!s.cost?['Cost allocation and contribution unverified']:[]),...(!s.floor?['Defined-scope floor missing']:[]),...(s.floor&&s.standard&&Math.round(s.standard*(10000-p.bookingBps-p.conversionBps)/10000)<s.floor?['Continuing promotion is below the legacy floor']:[]),...(s.scopeStatus==='provisional'?['Measurable scope caps require owner confirmation']:[]),...(s.premium&&!s.premiumScope?['Premium scope incomplete; premium selling disabled']:[])]}));}
