import { z } from 'zod';
import { publicServices, scopes } from './catalogue.ts';
const text=z.string().max(4000).default('');
export const registration=z.object({name:z.string().min(2).max(100),email:z.email().max(200),phone:z.string().regex(/^\+[1-9][0-9 ()-]{6,20}$/),company:z.string().min(2).max(200),country:z.string().min(2).max(60),industry:z.string().min(2).max(100),website:z.union([z.url(),z.literal('')]).default(''),serviceInterest:z.string().min(1).max(100),projectBudget:text,monthlyBudget:text,contactPermission:z.literal(true),marketingPermission:z.boolean().default(false),attribution:z.record(z.string().max(40),z.string().max(200)).default({})}).strict();
export const requirements=z.object({intent:text,services:z.array(z.string().refine(x=>publicServices.some(s=>s.id===x))).max(10),problem:text,goals:text,companySize:text,subsegment:text,audience:text,engagement:text,projectBudget:text,monthlyBudget:text,includesMedia:z.boolean().default(false),mediaBudget:z.number().int().min(0).max(100000000).default(0),term:text,languages:text,decisionMaker:text,startDate:text,deadline:text,assets:text,providers:text,constraints:text,notes:text,pages:z.number().int().min(1).max(200).default(5),products:z.number().int().min(0).max(10000).default(0),integrations:z.number().int().min(0).max(100).default(0),customLogin:z.boolean().default(false),uncertain:z.boolean().default(false),assumptionsConfirmed:z.boolean().default(false),details:z.record(z.string().max(50),z.string().max(3000)).default({})}).strict();
export const questions:Record<string,string[]>={website:['New or rebuild, and what should visitors do?','Standard pages, unique templates and portfolio project count','Copy and image owner; existing branding','Editing, CMS, blog, forms and routing','Bookings, payments, permissions, dashboard, inventory and search','Integrations, migration, languages and accessibility','Tracking, hosting and maintenance'],social:['Platforms, audience and goals','Unique assets, cross-posting and static/carousel mix','Reel length, supplied footage or original filming','Monthly material, captions, language and founder content','Community volume, approval owner, reports and meetings','Paid distribution and duration'],brand:['New identity, refresh or logo only','Naming, strategy, concepts and stakeholder count','Revisions, collateral, guide depth and file formats','Existing assets and trademark expectations'],search:['Domain, locations, regions and services','Site condition, content owner and migration risk','Analytics, Search Console and GBP eligibility/access','Languages, competition and previous work'],paid:['Platform, objective, offer and target area','Media budget and account history','Landing page, tracking and creative availability','Response owner, qualification and follow-up process'],video:['Editing or production, footage and length','Aspect ratios, captions, voiceover and music rights','Models, drawings, scenes and assets','Resolution, camera route, render needs, revisions and deadline'],care:['Stack, hosting ownership and current condition','Issues, backups, update frequency and support hours','Monitoring and response expectations'],systems:['Users, roles and process steps','Existing systems, APIs, integrations and sensitive data','Migration volume, source systems and exceptions','Human approvals, task volume, support and success criteria']};
export function recommend(r:any,market:string,p:any){let ids=[...(r.services||[])];if(!ids.length){const text=(r.problem+' '+r.goals+' '+r.intent).toLowerCase();ids=/brand|identity|logo/.test(text)?['logo']:/social|content/.test(text)?['social']:/search|local/.test(text)?['local-seo']:['portfolio'];}
 ids=[...new Set(ids)];if(ids.includes('business'))ids=ids.filter(x=>x!=='portfolio'&&x!=='landing');if(ids.includes('portfolio'))ids=ids.filter(x=>x!=='landing');if(ids.includes('identity'))ids=ids.filter(x=>x!=='logo');
 const reasons:string[]=[];if(!['IN','AE','GB','US'].includes(market))reasons.push('market_review');if(r.pages>p.reviewLimits.pages)reasons.push('page_scope');if(r.products>p.reviewLimits.products)reasons.push('product_scope');if(r.integrations>p.reviewLimits.integrations)reasons.push('integration_complexity');if(r.customLogin)reasons.push('technical_discovery');if(r.languages&&!/^english$/i.test(r.languages))reasons.push('localization_review');if(r.uncertain&&!r.assumptionsConfirmed)reasons.push('material_assumptions_unconfirmed');
 const services=ids.map(id=>{const s=publicServices.find(s=>s.id===id)!;if(['C','D'].includes(s.readiness)||!scopes[id])reasons.push(id+':owner_or_partner_review');if(scopes[id]?.caps.pages&&r.pages>scopes[id].caps.pages)reasons.push(id+':additional_pages');return{...s,scope:scopes[id]||{deliverables:['A discovery discussion and defined next step'],supplies:['Available assets and system information'],exclusions:['Implementation until capability and costs are confirmed'],timeline:'Confirmed after discovery'}};});
 return{services,reasons,assumptions:r.uncertain?['Assume a brochure/portfolio website, supplied copy and images, a contact form and no custom login. Please confirm or revise these assumptions.']:[],nextStep:'Review this scope with Arjun; booking unlocks the provisional estimate.',budgetNote:'Your budget helps us choose a feasible scope. Identical work keeps the same price. Smaller budgets and “not sure” are welcome.'};}
export function alternatives(r:any){const current=r.services.length?r.services:['portfolio'];const choices=[{id:'recommended',name:'Your recommended scope',requirements:{...r,services:current}},{id:'focused',name:'A more focused first phase',requirements:{...r,services:current.length>1?[current[0]]:current.map((s:string)=>s==='business'?'portfolio':s==='portfolio'?'landing':s==='identity'?'logo':s),pages:current.includes('portfolio')?1:Math.min(r.pages,7)}}];return choices.filter((x,i,a)=>a.findIndex(y=>JSON.stringify(y.requirements.services)===JSON.stringify(x.requirements.services))===i);}
