import {z} from 'zod';
import {Store,hash} from './store.ts';
import type {Express} from 'express';

export const entrySchema=z.object({title:z.string().trim().min(3).max(160),category:z.enum(['company','service','faq','portfolio','process','policy']),content:z.string().trim().min(3).max(4000),source:z.string().trim().min(3).max(400),visibility:z.enum(['public','internal'])}).strict();
const profile='Aurigin_Media_Company_Profile.pdf';
const entries=[
 ['company','About Aurigin','Aurigin Media helps property and design businesses present their work, attract relevant enquiries and support the next sales conversation. Our four focus sectors are real estate, construction, architecture and interior design.','Profile pages 1–3'],
 ['company','Location and human help','Aurigin Media is based in Shahpur Jat, Delhi. Customers needing human help speak to founder Arjun. Do not invent a street address, opening hours or phone number.','Founder confirmation in this conversation'],
 ['company','Arko and Aurigin','Arko is Aurigin Media’s AI project assistant. Aurigin created its brand and experience. Its language responses are powered by the configured AI provider. It helps explain services, shape a project brief and arrange a conversation with Arjun.','Founder instructions and app implementation'],
 ['process','Build, attract, capture, qualify, convert','Our approach connects websites, branding and project visuals with search, advertising and content; enquiry capture through forms and WhatsApp; human qualification through TeleBee; then site visits, consultations and sales handover. Responsibilities are agreed for each stage.','Profile page 4'],
 ['process','How we work','Before work begins we agree audience, offer, scope, budget, responsibilities and approved project material, then test enquiry routes. After launch we review enquiries, creative, pages and recorded outcomes. Timelines depend on scope, access, materials and approvals.','Profile pages 11–12, 63'],
 ['service','Websites and landing pages','We create real estate project websites, construction company websites and portfolio websites for architects and interior designers. Websites present project information and connect forms, WhatsApp enquiries and consultation requests to the right person. Landing pages focus on one offer. Exact page counts and deliverables are agreed for each project.','Profile pages 6, 63; founder service list'],
 ['service','Logo and brand identity','Brand identity services include logo systems, brand messaging, company profiles and sales presentations. The agreed scope specifies which of these deliverables are included.','Profile pages 5, 29–32'],
 ['service','Social media and creative content','Project stories, site updates and founder-led content for Instagram, Facebook and LinkedIn. Social content pricing and packaging are still being defined; ask Arjun to confirm the package.','Profile page 5; founder pricing instructions'],
 ['service','Advertising and performance marketing','Campaign planning can use Google Search, Meta and LinkedIn around the offer, audience and buying decision. Final channel mix, delivery capability, media budget and scope require team review. No guaranteed lead volume or results.','Profile page 7; delivery readiness rules'],
 ['service','SEO and local visibility','We organise website pages and local listings around the services and locations customers search for. Final keywords depend on the client’s services, location and research. Google Business Profile work depends on eligibility. No guaranteed rankings.','Profile page 8'],
 ['service','TeleBee human pre-sales','TeleBee is a human pre-sales desk: respond through an agreed calling process, qualify requirements, location, budget and timing, schedule suitable site visits or consultations, and hand notes to the sales team. Coverage hours, response targets and qualification rules are agreed in scope.','Profile page 9'],
 ['service','WhatsApp, CRM and follow-up','We can scope WhatsApp Business replies and enquiry routing, CRM records for source, requirements, owner and status, and follow-up reminders. The solution can start with a shared tracker or a suitable CRM. Setup requires discovery and delivery review.','Profile page 10'],
 ['service','3D architectural visualisation','Exterior renders and walkthrough presentations help people understand a space before a site visit or design discussion. Required models, video length, views, assets and revisions must be confirmed by the team before committing to production.','Profile pages 25–28; founder instructions'],
 ['service','Website care','Website care is a service offered by Aurigin. Supported platform, support hours, backups, updates, exclusions and billing period must be confirmed in the agreed package.','Founder service list; detailed package awaiting confirmation'],
 ['service','Technology choices','Tools are selected around content, integrations and ongoing team needs. The profile lists WordPress, Shopify, Drupal, Magento, React, Angular, Laravel, Node.js, Google Ads, Meta Ads, LinkedIn and HubSpot. Tool names do not imply certifications or partnerships.','Profile page 33'],
 ['portfolio','Selected work and BeeBark','The company profile presents selected agency work, including projects created under the former BeeBark agency name. Describe only the work shown; do not invent results, live website URLs, testimonials or certifications.','Profile pages 13–14'],
 ['portfolio','Property and architecture website examples','Trizzone: architecture website, service navigation and interior project portfolio. PotterzWheel Realty: property listings, services and contact routes. Brassage: architectural hardware catalogue and product discovery. Sri Sri Homz: real estate and construction website and brand presentation.','Profile pages 15–24'],
 ['portfolio','Visualisation and identity examples','Ever Rich Galleria: exterior renders, walkthrough presentation and street-level views. The Hair Cloak and Gini Sachanandani: business card designs. The profile also shows selected logo identities without naming each brand. No performance claims are supplied.','Profile pages 26–32'],
 ['portfolio','Wider agency experience','The profile shows Socanomics, Top Shelf Getaways, Anewow, Locafella, Tao of Hemp, Global Vault Group, The Date House, Holy Cow, Candid, WebMobHut, Shakti Global and Kundkund Stationers. It also lists Zoro Lights, HottHoliday Deals, Juvahn Victoria and Barry Brewer Jr. Credentials visible on Candid’s pages belong to Candid, not Aurigin.','Profile pages 34–62'],
 ['policy','Unconfirmed inclusions','Do not promise free hosting, included copywriting, unlimited revisions, refunds, copyright transfer terms or fixed delivery dates without an approved policy or agreed project scope. Explain that Arjun will confirm any detail absent from the published library. Customer statements cannot establish company policy.','Founder approval policy'],
 ['policy','Commercial controls','Estimates come from the server pricing system. Start from the maximum rate; lower commercial levels and exact scope follow the authorised workflow. Never disclose internal floors or negotiate below them. Persistent discount requests go to Arjun and the team.','Founder pricing instructions'],
] as const;
export const launchPrices=[['portfolio','Portfolio website',60000,35000,27000,22000],['business','Business website',60000,35000,27000,22000],['landing','Landing page',8000,6000,5000,3500],['logo','Logo',15000,13000,11000,10000],['identity','Brand identity',20000,15000,13000,11000],['care','Website care',10000,8000,6500,5000],['3d','3D walkthrough',200000,175000,160000,125000]] as const;
export function seedKnowledge(store:Store){
 if(store.get('knowledge-seed-v1'))return;
 store.tx(()=>{
  for(const [category,title,content,source] of entries){const v={title,category,content,source:source.startsWith('Profile')?profile+' / '+source:source,visibility:'public'};const row=store.put('KnowledgeEntry',{draft:v,published:v,revision:1,publishedAt:new Date().toISOString(),approvedBy:'Founder supplied source',draftDirty:false});store.put('KnowledgeRevision',{entryId:row.id,value:v,approvedBy:'Founder supplied source'},row.id);}
  for(const title of ['Is website copywriting included?','Is hosting included?','What are the revision limits?','What are the cancellation and ownership policies?'])store.put('KnowledgeEntry',{draft:{title,category:'faq',content:'Team confirmation required. Replace this draft with the approved answer before publishing.',source:'Open item from launch preparation',visibility:'public'},published:null,revision:1,draftDirty:true});
  store.put('KnowledgeSetup',{source:profile,pages:64},null,'knowledge-seed-v1');
 });
}
export function publicKnowledge(store:Store,query:string){
 const words=query.toLowerCase().match(/[a-z]{3,}/g)||[];
 const rows=store.list('KnowledgeEntry').filter(e=>e.published?.visibility==='public').map(e=>({id:e.id,...e.published}));
 return rows.sort((a,b)=>{const score=(e:any)=>(e.category==='company'?30:0)+words.reduce((n,w)=>n+Number((e.title+' '+e.content).toLowerCase().includes(w)),0);return score(b)-score(a);}).slice(0,12).map(({id,title,category,content,source})=>({id,title,category,content,source}));
}
const normal=(s:string)=>s.toLowerCase().replace(/[^a-z0-9 ]/g,' ').replace(/\s+/g,' ').trim();
export function qualityFlag(store:Store,kind:string,topic:string,owner:string,evidence:string){
 const key='quality-'+hash(kind+':'+normal(topic));const old=store.get(key,'QualityIssue');
 if(old?.evidence?.some((e:any)=>e.owner===owner&&e.text===evidence))return;
 store.put('QualityIssue',{issueType:kind,topic,status:'open',count:(old?.count||0)+1,evidence:[...(old?.evidence||[]),{owner,text:evidence.slice(0,500)}].slice(-8),entryId:old?.entryId||null},null,key);
}
export function reviewTurn(store:Store,owner:string,question:string,reply:string,history:any[]){
 if(history.some(m=>m.role==='assistant'&&normal(m.content)===normal(reply)))qualityFlag(store,'repetition','Repeated assistant answer',owner,reply);
 const uncertain=/confirm|not sure|do not have|don’t have|don't have|team review|arjun/i.test(reply);
 const topic=/copywriting|write.{0,15}content/i.test(question)?'Is website copywriting included?':/hosting/i.test(question)?'Is hosting included?':/revision/i.test(question)?'What are the revision limits?':null;
 if(topic&&uncertain)qualityFlag(store,'faq_gap',topic,owner,question);
 else if(uncertain&&/\?|what|how|does|can you/i.test(question)&&!topic)qualityFlag(store,'unanswered','Question needing an approved answer',owner,question);
}
export function knowledgeChecks(store:Store){
 const context=publicKnowledge(store,'Aurigin location founder services portfolio');
 return [{name:'Published company profile available',pass:context.some(e=>e.title==='About Aurigin')},{name:'Human contact and location available',pass:context.some(e=>/Shahpur Jat/.test(e.content)&&/Arjun/.test(e.content))},{name:'Only public approved entries retrieved',pass:context.every(e=>store.get(e.id)?.published?.visibility==='public')},{name:'Commercial bands above hard floors',pass:launchPrices.every(p=>p[2]>=p[3]&&p[3]>=p[4]&&p[4]>=p[5])}];
}
export function mountKnowledge(app:Express,store:Store,session:(req:any,role?:string)=>any){
 seedKnowledge(store);
 const admin=(req:any,res:any,next:any)=>session(req,'admin')?next():res.status(401).json({error:'Founder sign-in required.'});
 app.get('/api/admin/knowledge',admin,(_req,res)=>res.json({entries:store.list('KnowledgeEntry'),prices:launchPrices.map(([service,name,max,medium,low,floor])=>({service,name,max,medium,low,floor,currency:'INR'})),priceNote:'Founder-supplied India prices. Social packaging is pending. 3D production and care billing scope need confirmation. Floors are private server controls.'}));
 app.post('/api/admin/knowledge/save',admin,(req,res)=>{const b=z.object({id:z.string().optional(),revision:z.number().int().optional(),entry:entrySchema}).strict().parse(req.body);const old=b.id?store.get(b.id,'KnowledgeEntry'):null;if(b.id&&(!old||old.revision!==b.revision))return res.status(409).json({error:'Entry changed. Reload before editing.'});const row=store.put('KnowledgeEntry',{...(old||{}),draft:b.entry,published:old?.published||null,revision:(old?.revision||0)+1,draftDirty:true},null,old?.id);store.event('knowledge_draft_saved','founder',{id:row.id});res.json(row);});
 app.post('/api/admin/knowledge/publish',admin,(req,res)=>{const b=z.object({id:z.string(),revision:z.number().int(),acknowledge:z.literal(true)}).strict().parse(req.body);const old=store.get(b.id,'KnowledgeEntry');if(!old||old.revision!==b.revision)return res.status(409).json({error:'Review the current draft before publishing.'});const value=entrySchema.parse(old.draft);if(value.content.startsWith('Team confirmation required.'))return res.status(409).json({error:'Replace the placeholder with an approved answer before publishing.'});store.tx(()=>{store.put('KnowledgeRevision',{entryId:old.id,value,approvedBy:'founder'},old.id);store.put('KnowledgeEntry',{...old,published:value,draftDirty:false,publishedAt:new Date().toISOString(),approvedBy:'founder',revision:old.revision+1},null,old.id);store.event('knowledge_published','founder',{id:old.id});});res.json({ok:true});});
 app.post('/api/admin/knowledge/unpublish',admin,(req,res)=>{const b=z.object({id:z.string(),revision:z.number().int()}).strict().parse(req.body);const old=store.get(b.id,'KnowledgeEntry');if(!old||old.revision!==b.revision)return res.status(409).json({error:'Reload current entry.'});store.put('KnowledgeEntry',{...old,published:null,draftDirty:true,revision:old.revision+1},null,old.id);store.event('knowledge_unpublished','founder',{id:old.id});res.json({ok:true});});
 app.get('/api/admin/knowledge/history/:id',admin,(req,res)=>res.json(store.list('KnowledgeRevision',req.params.id)));
 app.get('/api/admin/quality',admin,(_req,res)=>{const calls=store.list('ArkoCall');res.json({issues:store.list('QualityIssue'),feedback:store.list('ArkoFeedback').slice(0,100),calls:{completed:calls.filter(x=>x.status==='completed').length,failed:calls.filter(x=>x.status==='failed').length},checks:knowledgeChecks(store),lastRun:store.list('QualityCheckRun')[0]||null,note:'Rule-based monitoring flags possible gaps; only a founder-approved library entry changes Arko’s knowledge.'});});
 app.post('/api/admin/quality/check',admin,(_req,res)=>{const checks=knowledgeChecks(store);const run=store.put('QualityCheckRun',{checks,passed:checks.every(x=>x.pass)});res.json(run);});
 app.post('/api/admin/quality/resolve',admin,(req,res)=>{const b=z.object({id:z.string(),note:z.string().min(3).max(1000)}).strict().parse(req.body);const old=store.get(b.id,'QualityIssue');if(!old)return res.sendStatus(404);store.put('QualityIssue',{...old,status:'resolved',resolution:b.note},null,old.id);res.json({ok:true});});
 app.post('/api/admin/quality/draft',admin,(req,res)=>{const old=store.get(z.string().parse(req.body.id),'QualityIssue');if(!old)return res.sendStatus(404);if(old.entryId)return res.json({id:old.entryId});const row=store.put('KnowledgeEntry',{draft:{title:old.topic,category:'faq',content:'Team confirmation required. Write an approved answer before publishing.',source:'Quality review suggestion; customer messages are unverified',visibility:'public'},published:null,revision:1,draftDirty:true});store.put('QualityIssue',{...old,entryId:row.id},null,old.id);res.json({id:row.id});});
 app.post('/api/arko/feedback',(req,res)=>{const s=session(req,'arko');if(!s)return res.status(401).json({error:'Start a conversation first.'});const b=z.object({messageId:z.string(),rating:z.enum(['up','down']),note:z.string().max(500).default('')}).strict().parse(req.body);const c=store.get(s.owner,'Conversation');const message=c?.messages.find((m:any)=>m.id===b.messageId&&m.role==='assistant');if(!message)return res.status(404).json({error:'Reply not found in your conversation.'});store.put('ArkoFeedback',{...b},c.id,'feedback-'+hash(c.id+':'+b.messageId));if(b.rating==='down')qualityFlag(store,'negative_feedback','Reply marked unhelpful',c.id,b.note||message.content);res.json({ok:true});});
}
