import { z } from 'zod';
export const policySchema=z.object({
 productName:z.string().min(1).max(80),timezone:z.string().refine(s=>{try{new Intl.DateTimeFormat('en',{timeZone:s});return true;}catch{return false;}}),
 slotMinutes:z.number().int().min(15).max(180),bufferMinutes:z.number().int().min(0).max(120),noticeHours:z.number().int().min(0).max(168),horizonDays:z.number().int().min(1).max(90),dailyCap:z.number().int().min(1).max(4),
 workStart:z.string().regex(/^\d\d:\d\d$/),workEnd:z.string().regex(/^\d\d:\d\d$/),blackouts:z.array(z.string()),blocks:z.array(z.object({start:z.string().datetime(),end:z.string().datetime()})),
 validityDays:z.number().int().min(1).max(90),bookingBps:z.number().int().min(0).max(1600),conversionBps:z.number().int().min(0).max(1600),negotiationBps:z.array(z.number().int().min(0).max(1600)).min(1).max(3),
 indiaPriority:z.number().int().positive(),internationalPriority:z.number().int().positive(),inclusive:z.boolean(),contributionBps:z.number().int().min(0).max(9000),
 retentionDays:z.number().int().min(30),budgetThresholds:z.record(z.string(),z.number().int().nonnegative().nullable()),benefitDays:z.number().int().positive(),benefitHours:z.number().int().nonnegative(),benefitCost:z.number().int().nonnegative(),benefitEnabled:z.boolean(),
 referralReward:z.number().int().nonnegative().nullable(),referralCap:z.number().int().nonnegative().nullable(),reactivationPolicy:z.string(),fx:z.record(z.string(),z.object({inrMicrosPerUnit:z.number().int().positive(),date:z.string(),source:z.string()})),fxMaxAgeDays:z.number().int().positive(),
 reviewLimits:z.object({pages:z.number().int().positive(),products:z.number().int().nonnegative(),integrations:z.number().int().nonnegative()}),terms:z.string().max(6000),taxBps:z.number().int().min(0).max(10000).nullable(),taxApproved:z.boolean()
}).strict().refine(p=>p.bookingBps+p.conversionBps<=10000&&p.workStart<p.workEnd,'Invalid policy');
export type Policy=z.infer<typeof policySchema>;
export const defaultPolicy:Policy={productName:'Aurigin Project Planner',timezone:'Asia/Kolkata',slotMinutes:60,bufferMinutes:30,noticeHours:2,horizonDays:30,dailyCap:4,workStart:'10:30',workEnd:'17:30',blackouts:[],blocks:[],validityDays:15,bookingBps:1100,conversionBps:500,negotiationBps:[400,700,1000],indiaPriority:5000000,internationalPriority:10000000,inclusive:true,contributionBps:2000,retentionDays:365,budgetThresholds:{IN:1000000,AE:null,GB:null,US:null},benefitDays:30,benefitHours:1,benefitCost:0,benefitEnabled:false,referralReward:null,referralCap:null,reactivationPolicy:'Founder review required on cancellation, reactivation, renewals or unrelated services.',fx:{},fxMaxAgeDays:30,reviewLimits:{pages:15,products:50,integrations:2},terms:'Estimates depend on the stated scope and remain valid for 15 days. The same confirmed requirements normally retain the estimate. New pages, functionality, creative directions, missing assets or changed timing require a written change order. Consolidate feedback within agreed revision rounds. Payment delays may move delivery dates after discussion. Start dates and final scope are confirmed with Arjun. No ranking, revenue, lead or response-time guarantee.',taxBps:null,taxApproved:false};
