import { createHash } from 'node:crypto';
import type { Policy } from './policy.ts';
export const money=(x:number)=>{if(!Number.isSafeInteger(x)||x<0)throw new Error('Invalid money');return x;};
export function bps(n:number,b:number){money(n);if(!Number.isInteger(b)||b<0||b>10000)throw new Error('Invalid percentage');return Number((BigInt(n)*BigInt(b)+5000n)/10000n);}
export function milestones(n:number){const a=bps(n,4000),b=bps(n,3000);return[a,b,n-a-b];}
export function economics(net:number,floor:number|null,cost:number|null,benefit:number,p:Policy){money(net);money(benefit);if(floor===null||cost===null)return{allowed:false,reason:'Cost review required'};const required=Number((BigInt(cost+benefit)*10000n+BigInt(10000-p.contributionBps)-1n)/BigInt(10000-p.contributionBps));return{allowed:net>=floor&&net>=required,required:Math.max(required,floor),reason:net<floor?'Below scope floor':net<required?'Insufficient contribution':'Validated'};}
export function priority(netMonthly:number,market:string,p:Policy,date=Date.now()){let threshold=p.indiaPriority;if(market!=='IN'){const fx=p.fx[market];if(!fx||!Number.isFinite(Date.parse(fx.date))||date-Date.parse(fx.date)>p.fxMaxAgeDays*86400000||Date.parse(fx.date)>date)return{state:'review',basis:'converted recurring agency fee',reason:'Current dated FX reference required'};threshold=Number((BigInt(p.internationalPriority)*1000000n+BigInt(fx.inrMicrosPerUnit)-1n)/BigInt(fx.inrMicrosPerUnit));}return{state:(p.inclusive?netMonthly>=threshold:netMonthly>threshold)?'priority':'standard',basis:'converted recurring agency fee'};}
export function calculate(lines:any[],market:string,p:Policy,route='promotion',round=0){
 if(!['promotion','negotiated','custom'].includes(route))throw new Error('Invalid route');
 if(route==='negotiated'&&(round<1||round>p.negotiationBps.length))throw new Error('Round limit');
 const priced=lines.map(l=>{money(l.original);if(!Number.isInteger(l.quantity)||l.quantity<1||l.quantity>(l.maxQuantity||1))throw new Error('Quantity outside scope');const original=l.original*l.quantity;money(original);const eligible=l.eligible!==false;const discount=eligible?(route==='promotion'?p.bookingBps:route==='negotiated'?p.negotiationBps[round-1]:0):0;const booking=original-bps(original,discount);const converted=eligible&&route==='promotion'?original-bps(original,p.bookingBps+p.conversionBps):booking;return{...l,original,booking,converted,bookingDiscount:original-booking,conditionalDiscount:booking-converted,economics:eligible?economics(converted,l.floor,l.cost,l.benefitCost||0,p):{allowed:true,reason:'Excluded pass-through'}};});
 const totals=(cadence:string)=>priced.filter(l=>l.cadence===cadence).reduce((a,l)=>({original:a.original+(l.eligible!==false?l.original:0),booking:a.booking+(l.eligible!==false?l.booking:0),converted:a.converted+(l.eligible!==false?l.converted:0),excluded:a.excluded+(l.eligible===false?l.original:0)}),{original:0,booking:0,converted:0,excluded:0});
 const project=totals('project'),monthly=totals('monthly');const tax=p.taxApproved&&p.taxBps!==null?{project:bps(project.converted+project.excluded,p.taxBps),monthly:bps(monthly.converted+monthly.excluded,p.taxBps)}:null;
 return{route,round,lines:priced,project,monthly,tax,firstPeriod:milestones(project.converted)[0]+project.excluded+monthly.converted+monthly.excluded+(tax?.project||0)+(tax?.monthly||0),milestones:milestones(project.converted),priority:priority(monthly.converted,market,p),economicStatus:priced.every(l=>l.economics.allowed)?'validated':'review'};
}
export function fingerprint(x:unknown){return createHash('sha256').update(JSON.stringify(x)).digest('hex');}
export function publicPricing(q:any){return{route:q.route,round:q.round,project:q.project,monthly:q.monthly,tax:q.tax,firstPeriod:q.firstPeriod,milestones:q.milestones,priority:q.priority.state==='priority'?'Priority consultation preparation':q.priority.state==='review'?'Agency review':'Standard consultation',lines:q.lines.map((l:any)=>({service:l.service,name:l.name,quantity:l.quantity,unit:l.unit,cadence:l.cadence,eligible:l.eligible,original:l.original,booking:l.booking,converted:l.converted,bookingDiscount:l.bookingDiscount,conditionalDiscount:l.conditionalDiscount,scope:l.scope})),qualification:q.economicStatus==='review'?'Provisional scope and commercial eligibility require agency review.':'Subject to final scope confirmation.'};}
