import {readFileSync} from 'node:fs';
import { PDFDocument,StandardFonts,rgb } from 'pdf-lib';
export function proposalText(q:any){const c=q.currency;const fmt=(n:number)=>new Intl.NumberFormat('en',{style:'currency',currency:c,currencyDisplay:'code'}).format(n/100);return[
 `AURIGIN | ${q.demo?'DEMO - ':''}PROJECT PROPOSAL`,`${q.id} / version ${q.version}`,`${q.company} | ${q.market} | ${c}`,`Issued ${q.issued.slice(0,10)} | Valid until ${q.expires.slice(0,10)}`,`Status: ${q.status}`,`Needs: ${q.needs||'Defined scope below'}`,
 ...q.pricing.lines.flatMap((l:any)=>[l.name+' | '+l.cadence,...l.scope.deliverables.map((x:string)=>'  '+x),'Client supplies: '+l.scope.supplies.join('; '),'Excludes: '+l.scope.exclusions.join('; '),'Estimated timing: '+l.scope.timeline,`Original ${fmt(l.original)} | Booking ${fmt(l.booking)} | Conditional upon payment ${fmt(l.converted)}`]),
 `One-time eligible fees: ${fmt(q.pricing.project.original)}; booking ${fmt(q.pricing.project.booking)}; conditional final ${fmt(q.pricing.project.converted)}`,
 `Monthly eligible fees: ${fmt(q.pricing.monthly.original)}; booking ${fmt(q.pricing.monthly.booking)}; conditional final ${fmt(q.pricing.monthly.converted)}`,
 `Excluded project costs ${fmt(q.pricing.project.excluded)}; excluded monthly costs ${fmt(q.pricing.monthly.excluded)}`,
 `Project milestones (40/30/30): ${q.pricing.milestones.map(fmt).join(' / ')}`,
 `First period conditional cash requirement ${fmt(q.pricing.firstPeriod)}; monthly recurring ${fmt(q.pricing.monthly.converted+q.pricing.monthly.excluded)}`,
 'Project milestones: kickoff; approved design/creative direction (storyboard or low-resolution preview for 3D); before launch or editable files. Retainers billed in advance, normally 3-month initial commitment; SEO recommends 6 months.',
 q.pricing.tax?'Tax as separately configured in the estimate.':'Tax treatment awaits approved configuration; taxes are not represented as zero.',
 q.pricing.route==='promotion'?'Booking earns 11% of the original eligible agency fee. Payment earns another 5 percentage points: 16% total. The active-association entitlement does not expire at month three.':'Negotiated/custom route does not stack with booking or conversion promotions.',
 'Media, licences, hosting, travel, partner expenses and taxes are not eligible for the promotion. Benefits: '+(q.benefits||'No additional benefit is currently promised.'),
 q.pricing.qualification,...(q.reviewReasons.length?['Scope needing review: '+q.reviewReasons.join(', ')]:[]),q.terms,
 'Next step: discuss scope and delivery start with Arjun. Booking and this provisional proposal do not obligate purchase. Consultation remains required before initiation.'
 ];}
export async function pdf(q:any){const d=await PDFDocument.create();d.setTitle('Aurigin proposal '+q.id);const font=await d.embedFont(StandardFonts.Helvetica),bold=await d.embedFont(StandardFonts.HelveticaBold);const logo=await d.embedPng(readFileSync(new URL('../client/assets/aurigin-logo.png',import.meta.url)));const addPage=()=>{const p=d.addPage([595,842]);p.drawRectangle({x:0,y:832,width:595,height:10,color:rgb(32/255,72/255,216/255)});p.drawRectangle({x:50,y:747,width:495,height:3,color:rgb(1,228/255,92/255)});p.drawImage(logo,{x:48,y:752,width:108,height:72});p.drawText('YOUR PROJECT / AURIGIN MEDIA',{x:185,y:785,size:11,font:bold,color:rgb(32/255,72/255,216/255)});return p;};let page=addPage(),y=720;const clean=(s:string)=>s.replace(/[–—]/g,'-').replace(/[^\x20-\x7E]/g,' ');let index=0;for(const paragraph of proposalText(q)){const wrapped:string[]=[];let line='';for(const word of clean(paragraph).split(' ').flatMap(x=>x.match(/.{1,70}/g)||[''])){if(font.widthOfTextAtSize(line+word,10)>490){wrapped.push(line);line='';}line+=word+' ';}wrapped.push(line);if(y-wrapped.length*15<60&&wrapped.length<45){page=addPage();y=720;}for(const text of wrapped){if(y<60){page=addPage();y=720;}page.drawText(text,{x:50,y,size:index===0?12:10,font:index===0?bold:font,color:rgb(17/255,24/255,39/255)});y-=15;}y-=9;index++;}for(const [i,p] of d.getPages().entries())p.drawText(`Aurigin | ${q.demo?'Demo | ':''}Page ${i+1} of ${d.getPageCount()}`,{x:50,y:30,size:8,font,color:rgb(.33,.38,.47)});return Buffer.from(await d.save());}
